### ISSUE TITLE
IP does not appear to be an IPv4 or IPv6 network

### ISSUE THREAD

**Issue by kflinderman** [danielperna84/hass-configurator#109]
After upgrading to 0.75.2 and 1.1 on configurator, I keep get this error message. I cannot get into any instance of it, either through Hassio or the web ui. I don't know if it makes a difference but I'm running hassos as well. 

```---------------------------------------- Exception happened during processing of request from ('DESKTOP_IP', 50029) Traceback (most recent call last): File "/usr/local/lib/python3.6/socketserver.py", line 651, in process_request_thread self.finish_request(request, client_address) File "/usr/local/lib/python3.6/socketserver.py", line 361, in finish_request self.RequestHandlerClass(request, client_address, self) File "/usr/local/lib/python3.6/socketserver.py", line 721, in __init__ self.handle() File "/usr/local/lib/python3.6/http/server.py", line 418, in handle self.handle_one_request() File "/usr/local/lib/python3.6/http/server.py", line 406, in handle_one_request method() File "/configurator.py", line 4687, in do_GET super().do_GET() File "/configurator.py", line 3716, in do_GET if not check_access(self.client_address[0]): File "/configurator.py", line 3648, in check_access if ipobject in ipaddress.ip_network(net): File "/usr/local/lib/python3.6/ipaddress.py", line 84, in ip_network address) ValueError: '' does not appear to be an IPv4 or IPv6 network ----------------------------------------```

**Comment by danielperna84** [comment]
A [post in the forum](https://community.home-assistant.io/t/configurator-stopped-working-after-update-to-1-0/62582/39) reports that setting a value for the `allowed_networks` option as fixed some issues. You log output is very valuable to track this down. Can you confirm that setting `allowed_networks` fixes the issue for you as well?

**Comment by kflinderman** [comment]
Yup looks like that has resolved it.
