### ISSUE TITLE
Entity list not loading

### ISSUE THREAD

**Issue by paulandkirstie** [danielperna84/hass-configurator#112]
I am using the new HassOS (having moved over from the ResinOS version) and version 0.75.2 of hassio, Configurator no longer seems to load or allow searching of the list of entities. I am using version 1.1 of Configurator and have also tried restoring version 0.4 of configurator from a snapshot and observe the same behaviour.

**Comment by danielperna84** [comment]
Could you please provide the logoutput of the startup of the addon?

**Comment by paulandkirstie** [comment]
Here goes, hopefully this is what you need -

This is the system log on stopping and starting the addin.

18-08-08 22:57:47 INFO (SyncWorker_9) [hassio.docker.interface] Stop homeassistant/armhf-addon-configurator docker application
18-08-08 22:57:50 INFO (SyncWorker_9) [hassio.docker.interface] Clean homeassistant/armhf-addon-configurator docker application
18-08-08 22:58:01 INFO (SyncWorker_11) [hassio.docker.addon] Start docker addon homeassistant/armhf-addon-configurator with version 1.1

The log on the addin page shows the following:

INFO:2018-08-08 23:58:12,409:__main__:Starting server
INFO:2018-08-08 23:58:12,417:__main__:Listening on: https://0.0.0.0:3218

**Comment by danielperna84** [comment]
The second part is what I need. Although it doesn't show me what I need to see. I believe there's a button on the add-on site (where you configure and restart the add-on) that says something like _refresh logs_. Please press that button and hopefully the information I need will be appended.

**Comment by paulandkirstie** [comment]
There's a bit more information with a refresh after opening the configurator web ui


INFO:2018-08-09 00:06:10,984:__main__:Starting server
INFO:2018-08-09 00:06:10,992:__main__:Listening on: https://0.0.0.0:3218
INFO:2018-08-09 00:07:17,453:__main__:192.168.1.78 - "GET / HTTP/1.1" 200 -
WARNING:2018-08-09 00:07:17,580:__main__:Exception getting bootstrap
WARNING:2018-08-09 00:07:17,581:__main__:HTTP Error 502: Bad Gateway
INFO:2018-08-09 00:07:19,310:__main__:192.168.1.78 - "GET /api/listdir?path=. HTTP/1.1" 200 -

**Comment by danielperna84** [comment]
Is your Home Assistant running properly? The error indicates, that a connection to the API can not be established. That would be the case if for example you start the configurator add-on while HASS itself hasn't finished its startup process and thus does not provide API access. To make sure this is not the problem simply restart the configurator add-on while having the HASS UI opened and functional.

**Comment by DavidFW1960** [comment]
Hi Dan - I have an empty entity list as well. The dropdown arrow does nothing.

Here is the log:
```
WARNING:2018-08-09 09:02:45,980:__main__:Invalid value for BANNED_IPS. Using empty list.
INFO:2018-08-09 09:02:45,981:__main__:Starting server
INFO:2018-08-09 09:02:45,984:__main__:Listening on: http://0.0.0.0:3218
INFO:2018-08-09 09:28:30,254:__main__:Requesting authorization
INFO:2018-08-09 09:28:30,255:__main__:172.30.32.1 - "GET /sesame HTTP/1.1" 401 -
INFO:2018-08-09 09:28:36,001:__main__:172.30.32.1 - "GET /sesame HTTP/1.1" 302 -
INFO:2018-08-09 09:28:36,014:__main__:{'title': 'HASS Configurator - SESAME access', 'message': 'Your SESAME token has been used to whitelist the IP address 172.30.32.1.'}
WARNING:2018-08-09 09:28:36,202:__main__:Exception while creating notification: HTTP Error 502: Bad Gateway
INFO:2018-08-09 09:28:37,091:__main__:172.30.32.1 - "GET / HTTP/1.1" 200 -
WARNING:2018-08-09 09:28:37,141:__main__:Exception getting bootstrap
WARNING:2018-08-09 09:28:37,142:__main__:HTTP Error 502: Bad Gateway
INFO:2018-08-09 09:28:39,091:__main__:172.30.32.1 - "GET /api/file?filename=/config/configuration.yaml HTTP/1.1" 200 -
INFO:2018-08-09 09:28:39,225:__main__:172.30.32.1 - "GET /api/listdir?path=. HTTP/1.1" 200 -
INFO:2018-08-09 09:28:59,895:__main__:172.30.32.1 - "GET /api/listdir?path=/ HTTP/1.1" 200 -
```

Not sure why the time is jumping around. Currently 9:32AM here on Aug 9th. (we are UTC+10)

**Comment by danielperna84** [comment]
Could you please manually add the option `"loglevel": "debug"` and restart the add-on? In the beginning it will show all the options that are being passed to the configurator. Please redact secret values like the sesame or passwords. I mainly want to see what arrives as the value for the API-endpoint.

**Comment by danielperna84** [comment]
For me (HassOS VM for testing) I get `'HASS_API': 'http://hassio/homeassistant/api/'` and everything is working fine. I'm on HassOS 1.9, supervisor 123.

**Comment by danielperna84** [comment]
Please also try the following:
In the menu on the top right (three dots) there's an option all the way at the bottom called _Execute shell command`. In the Command-box enter the command `ping -c 3 hassio` and click an _EXECUTE_. After a few seconds the content should update. In my case I got the following result:
```bash
Command executed: ping -c 3 hassio: 0
PING hassio (172.30.32.2): 56 data bytes
64 bytes from 172.30.32.2: seq=0 ttl=64 time=0.038 ms
64 bytes from 172.30.32.2: seq=1 ttl=64 time=0.214 ms
64 bytes from 172.30.32.2: seq=2 ttl=64 time=0.193 ms

--- hassio ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.038/0.148/0.214 ms
```

**Comment by DavidFW1960** [comment]
Ok My config:
```
{
  "username": "my_user",
  "password": "my_pass",
  "ssl": false,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "allowed_networks": [
    "172.30.0.0/16"
  ],
  "banned_ips": [
    ""
  ],
  "banlimit": 5,
  "ignore_pattern": [
    "__pycache__"
  ],
  "dirsfirst": true,
  "enforce_basepath": false,
  "notify_service": "persistent_notification.create",
  "sesame": "my_sesame",
  "loglevel": "debug"
}
```

Log after restarting addon:
```
DEBUG:2018-08-09 10:13:41,566:__main__:Settings after looking at environment:
DEBUG:2018-08-09 10:13:41,567:__main__:{'VERIFY_HOSTNAME': False, 'HASS_API_PASSWORD': 'string', 'DIRSFIRST': True, 'IGNORE_PATTERN': ['__pycache__'], 'ENFORCE_BASEPATH': False, 'HASS_API': 'http://hassio/homeassistant/api/', 'NOTIFY_SERVICE': 'persistent_notification.create', 'PASSWORD': 'pass', 'USERNAME': 'user', 'GIT': True, 'BANNED_IPS': [''], 'IGNORE_SSL': False, 'BASEPATH': '/config', 'SESAME': 'sesame', 'BANLIMIT': 5, 'ALLOWED_NETWORKS': ['172.30.0.0/16'], 'LOGLEVEL': 'debug'}
WARNING:2018-08-09 10:13:42,588:__main__:Invalid value for BANNED_IPS. Using empty list.
INFO:2018-08-09 10:13:42,589:__main__:Starting server
INFO:2018-08-09 10:13:42,592:__main__:Listening on: http://0.0.0.0:3218
'''

Shell Command:
```
Command executed: ping -c 3 hassio: 0
PING hassio (172.30.32.2): 56 data bytes
64 bytes from 172.30.32.2: seq=0 ttl=64 time=0.499 ms
64 bytes from 172.30.32.2: seq=1 ttl=64 time=0.401 ms
64 bytes from 172.30.32.2: seq=2 ttl=64 time=0.437 ms

--- hassio ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.401/0.445/0.499 ms
```

**Comment by DavidFW1960** [comment]
oh bloody hell!!!!!! I did all that and posted a log for you and everything you asked for and it's GONE!!!!!!

**Comment by paulandkirstie** [comment]
Hi Dan, sorry for the delay.

Ping gives the following

Command executed: ping -c 3 hassio: 0
PING hassio (172.30.32.2): 56 data bytes
64 bytes from 172.30.32.2: seq=0 ttl=64 time=0.702 ms
64 bytes from 172.30.32.2: seq=1 ttl=64 time=0.304 ms
64 bytes from 172.30.32.2: seq=2 ttl=64 time=0.370 ms

--- hassio ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.304/0.458/0.702 ms

And here is the log with debug enables (passwords and external ip's obscured with xxxxxx)

DEBUG:2018-08-09 10:05:35,328:__main__:Settings after looking at environment:
DEBUG:2018-08-09 10:05:35,330:__main__:{'VERIFY_HOSTNAME': '', 'SSL_CERTIFICATE': 'ssl/fullchain.pem', 'HASS_API_PASSWORD': 'xxxxx', 'DIRSFIRST': False, 'IGNORE_PATTERN': ['__pycache__'], 'ENFORCE_BASEPATH': False, 'HASS_API': 'http://hassio/homeassistant/api/', 'NOTIFY_SERVICE': 'persistent_notification.create', 'SSL_KEY': 'ssl/privkey.pem', 'PASSWORD': 'xxxxx', 'USERNAME': 'xxxxx', 'GIT': True, 'BANNED_IPS': ['8.8.8.8'], 'IGNORE_SSL': False, 'BASEPATH': '/config', 'BANLIMIT': 0, 'ALLOWED_NETWORKS': ['192.168.0.0/16', '172.30.0.0/16', 'xxxxx', '192.168.1.78', '192.168.1.104', 'xxxxx'], 'LOGLEVEL': 'debug'}
INFO:2018-08-09 10:05:37,415:__main__:Starting server
INFO:2018-08-09 10:05:37,423:__main__:Listening on: https://0.0.0.0:3218
INFO:2018-08-09 10:06:38,102:__main__:Requesting authorization
INFO:2018-08-09 10:06:38,104:__main__:192.168.1.78 - "GET / HTTP/1.1" 401 -
INFO:2018-08-09 10:06:40,145:__main__:192.168.1.78 - "GET / HTTP/1.1" 200 -
WARNING:2018-08-09 10:06:40,376:__main__:Exception getting bootstrap
WARNING:2018-08-09 10:06:40,377:__main__:HTTP Error 502: Bad Gateway
INFO:2018-08-09 10:06:42,921:__main__:192.168.1.78 - "GET /api/listdir?path=. HTTP/1.1" 200 -
DEBUG:2018-08-09 10:06:42,926:__main__:Exception (no repo): /config
INFO:2018-08-09 10:06:48,491:__main__:192.168.1.78 - "GET /favicon.ico HTTP/1.1" 200 -
INFO:2018-08-09 10:06:48,493:__main__:192.168.1.78 - "GET /favicon.ico HTTP/1.1" 404 -

My config is as follows:

{
  "username": "xxxxx",
  "password": "xxxxx",
  "ssl": true,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "allowed_networks": [
    "192.168.0.0/16",
    "172.30.0.0/16",
    "xxxxx",
    "192.168.1.78",
    "192.168.1.104",
    "xxxxx"
  ],
  "banned_ips": [
    "8.8.8.8"
  ],
  "banlimit": 0,
  "ignore_pattern": [
    "__pycache__"
  ],
  "dirsfirst": false,
  "enforce_basepath": false,
  "notify_service": "persistent_notification.create",
  "loglevel": "debug"
}

One thing that has occurred to me is that I am using the pihole addin and its DHCP server. Could this be blocking something?

Thanks

**Comment by danielperna84** [comment]
Thank you both for posting those details. To me it doesn't make any sense that it is not working since everything is looking as it should. You both generally are able to contact the hassio host, so connectivity is not an issue. The 502 error indicates, that the server side (Home Assistant in this case) has some problems.

As stated above, my test-VM is HassOS 1.9 with supervisor 123, and also the latest Home Assistant version. What are your versions?
And another thing that might help: try rebooting your machines.

**Comment by danielperna84** [comment]
The error you see is just a debug-message. It always comes up when you browse to a folder that is not a git repository. So if you haven't setup git, then the message is correct.

Besides that I have no clue what the problem you both have could be. My next best guess would be, that the pihole add-on messes around with the access to the API. @DavidFW1960 do you have the pihole add-on running as well?

**Comment by danielperna84** [comment]
[This](https://community.home-assistant.io/t/home-assistant-restarts-every-10-minutes/62951/) issue indicates, that some hassio users have troubles with the `trusted_netorks` option not being set. Maybe this prevents the configurator from accessing the API in some cases.

**Comment by paulandkirstie** [comment]
Updating to the latest supervisor did the trick, thanks very much for all your help.

**Comment by DavidFW1960** [comment]
Hi Dan - nope. No PiHole and latest HA and Supervisor. now 0.75.3 and 125 (I think). Updated this morning.

Entities list is working now for me.

**Comment by danielperna84** [comment]
Ok, so then this is not a problem with the configurator but with hassio itself. Hence I'll close this issue.
