### ISSUE TITLE
Cant Install on Hass.io

### ISSUE THREAD

**Issue by m50008** [danielperna84/hass-configurator#115]
I want to install the program using the add-on store and get the error:
18-08-13 12:38:10 INFO (SyncWorker_19) [hassio.docker.interface] Pull image homeassistant/armhf-addon-configurator tag 1.2.
18-08-13 12:38:12 ERROR (SyncWorker_19) [hassio.docker.interface] Can't install homeassistant/armhf-addon-configurator:1.2 -> 500 Server Error: Internal Server Error ("readlink /var/lib/docker/overlay2: invalid argument").

**Comment by danielperna84** [comment]
I'm pretty sure that's a temporary issue with the repository server. Please try again later. If the issue persists, please open an issue at the add-on repository: https://github.com/home-assistant/hassio-addons
This repository is about the configurator itself, not the add-on infrastructure.
