### ISSUE TITLE
Cannot paste from mobile browser

### ISSUE THREAD

**Issue by jlabs** [danielperna84/hass-configurator#116]
I more often than not use my phone to edit YAML files (it's just easier for me to make quick edits from my phone than get the laptop out), but I don't get the option to paste text into the editor.
I've only tried FireFox on iOS, but I'm sure I've read that all browsers on iOS have to use WebKit so technically they'd render pages the same (or very close).

**Comment by danielperna84** [comment]
The used editor has limited capabilities on mobile devices. There's already an issue about the inability to highlight text here: https://github.com/danielperna84/hass-configurator/issues/27
If it's ok for you I would change the title of that issue to generic mobile problems, and you re-post your issue there.
