### ISSUE TITLE
404 .com/api/listdir?path=. 404 (Not Found) 

### ISSUE THREAD

**Issue by gempir** [danielperna84/hass-configurator#119]
I run my home assistant on a .com domain with SSL and nginx. Hass-configurator runs via `.com/configurator-embed` it's a simple nginx reverse proxy. 

```nginx
location /configurator-embed {
        proxy_pass http://127.0.0.1:3128/;
}
```

When I try to load it I get this error .com/api/listdir?path=. 404 (Not Found)
I assume because the JS tries to load from my original base path and doesn't use the proxy prefix configurator-embed. So there should be an option to configure the base path of the hass-configurator.

**Comment by danielperna84** [comment]
This should be working since version 0.2.5. Here's the related issue: https://github.com/danielperna84/hass-configurator/pull/75
Could you please try to append a `/` to your nginx configuration? Reverse Proxies usually need that because you're forwarding a _directory_, not just a single resource. For a single file it would be correct like it is. But you couldn't access a static HTML page with additional CCS files etc. that way either.

**Comment by gempir** [comment]
This isn't really possible. The correct solution would be configuring the base path I think. 

Did you test the solution with apache as an iframe embed in home assistant? Because if I for example have a site called /configurator on my home assistant which is just the iframe of /configurator-embed the URL will still be /configurator. 

I'm not 100% sure how that works with iFrames because I thought it would try to load /api stuff from /configurator-embed. Since an iFrame can't really "talk" to the outside of its frame. So where is it getting the url from?

**Comment by danielperna84** [comment]
> This isn't really possible. The correct solution would be configuring the base path I think.

No. A stable web application should work _transparently_, no matter if placed behind a reverse proxy or not. So it has to figure out its base on the fly. Requiring to set a basepath would prohibit to run the same application on different domains with different subfolders.

Don't worry about the iframe. Consider it as being a completely different browser window. It does all the logic by itself.

The link you have provided uses the appended `/` just like I have said. It has to be there. And once that's correct, you should be able to open the configurator by browsing to `.com/configurator-embed/`. The trailing `/` __is__ important. And the same URL (__with__ trailing `/`) is what you point to for the iframe. Think of it like browsing to Google. You don't browse to `google.com/index.htm`. The specific resource for the base `.../` is provided by the web-application. The configurator does the same. It has no named resource you can open. It's just `/`, nothing else.

**Comment by gempir** [comment]
Alright. You're right. And if you had it working behind Apache, I'll have to figure out what's my issue with nginx. But since this isn't an issue with this project. I'm closing this issue. Thanks for the help
