### ISSUE TITLE
Configurator slide-out sidebar content disappearing on large monitor

### ISSUE THREAD

**Issue by nsina** [danielperna84/hass-configurator#121]
The content in the sidebar simply disappears. If I zoom in Chrome browser to 110%, the content shows up in the sidebar again.

<img width="377" alt="hassio issue" src="https://user-images.githubusercontent.com/4546547/46105359-af918f80-c18a-11e8-9883-059447b17037.PNG">

<img width="954" alt="hassio 2" src="https://user-images.githubusercontent.com/4546547/46105375-b1f3e980-c18a-11e8-9003-5ade9b82dc57.PNG">

**Comment by danielperna84** [comment]
At what Zoom level is the first screenshot taken? At 100% I see everything regardless of which browser / platform I use. At different Zoom levels I can confirm your observation. Troubles at different Zoom levels have been present before. But I personally don't feel the need to reliably support other levels than 100%.

**Comment by nsina** [comment]
It's actually at 100% that I see this issue.

![image](https://user-images.githubusercontent.com/4546547/46121862-a4f6ea80-c1ca-11e8-8d97-4f5057fee722.png)

**Comment by nsina** [comment]
Yup, it does. I think adding the `!important` property fixes whatever was happening, in addition to the width. Will close ticket.
