### ISSUE TITLE
Webui messed up.

### ISSUE THREAD

**Issue by apedance** [danielperna84/hass-configurator#129]
https://imgur.com/a/HHbgXzQ

Tried to reinstall and reset config.
No change.
Not usable right now.

**Comment by danielperna84** [comment]
Please try another browser. What you are seeing is because your browser for some reason fails to render the stylesheet embedded into the configurator.

**Comment by apedance** [comment]
Same with Firefox, Safari, Internet Explorer, Microsoft Edge.

**Comment by danielperna84** [comment]
No, it has been like that from the very beginning. So I don't know why this suddenly causes problems. But I tend to disagree, that the Cloadflare CDN should be on that blocklist. It's one of THE major CDNs that even lots of corprate websites use. 🤔 

Anyways, issue resolved, so I'm closing this.
