### ISSUE TITLE
Enable minimal view option to file explorer

### ISSUE THREAD

**Issue by sagilo** [danielperna84/hass-configurator#130]
Currently, the file explorer is really condensed and it's sometimes difficult to find the wanted file.
I'd be happy to see a plain minimal file explorer that shows only the files/directories names for easier navigation.

https://i.imgur.com/D9QxERS.png#

**Comment by danielperna84** [comment]
Do I understand correctly, that you want an option to have the file details (size, date etc.) hidden?

**Comment by sagilo** [comment]
Exactly.. displaying only the icon and the file/dir name
