### ISSUE TITLE
No entities being loaded to confifurator

### ISSUE THREAD

**Issue by DaveGalbraith** [danielperna84/hass-configurator#135]
I am running Home Assistant on Hassbian and having trouble running the configurator (v 0.3.3) as the entity list is blank. Any help to debug is much appreciated

**Comment by danielperna84** [comment]
I mean the log of the configurator. But the part you have posted look normal. Keep an on the logs and within the configurator click on `Reload core`. That should generate some output in the log, and possibly also some sort of error message.

**Comment by DaveGalbraith** [comment]
I'm still not clear where to see the configurator log, but reloading core gets me this on command line:
 INFO:2018-12-15 20:37:34,919:__main__:192.168.1.23 - "GET /api/reload_core HTTP/1.1" 200 -
INFO:2018-12-15 20:37:34,920:__main__:/api/reload_core
WARNING:2018-12-15 20:37:34,940:__main__:HTTP Error 401: Unauthorized

**Comment by danielperna84** [comment]
That is the log of the configurator. And there you see that it's lacking authentication. So you either have to use the deprecated API-password, or create a long lived access token. There are ways of not needing authentication at all, but that would dramatically decrease the security of Home Assistant. So just create the token and use it as the API password and you're good to go. You do that by going to your profile in Home Assistant (in the menu on the left, the badge at the top, and on the following page all the way at the bottom).

**Comment by DaveGalbraith** [comment]
Sorted.

Vielen Dank.
