### ISSUE TITLE
Support allowed domains in addition to allowed IP

### ISSUE THREAD

**Issue by michthom** [danielperna84/hass-configurator#143]
Hi there
I really like Configurator, and use it on all of my Home Assistant instances. But managing them remotely is more nerve-racking than I'd like (despite setting strong passwords and Sesame) since I need to open up the allowed IP range very widely.
Might it be possible to add selected DNS domains to the whitelist, such that if a connections arrives from any IP address to which a DNS records resolved, it would be allowed?
In this use case I have a DDNS record updated with the current IP address of my mobile device, I configure the DDNS domain name in Configurator, and when I connect, it iterates all allowed domains looking for a match with the IP address I connected with?
In that way I'd be able to keep allowed networks to the local subnets, and would only allow remote connections from trusted devices even when they change IP address?

**Comment by danielperna84** [comment]
I thought of this before, but did't think this was really practical. The Python code to resolve an IP address to a host name would be:

```python
import socket
socket.gethostbyaddr("8.8.8.8")
('google-public-dns-a.google.com', [], ['8.8.8.8'])
```
I have several DNS entries for my home, and using this function only returns the hostname my ISP has assigned to my IP address. And with the socket-module it's not possible to use alternative DNS servers. Because the configurator only uses build-in modules for core functionality I can't make use of other DNS libraries.

Does the Python code above acutally resolve to the hostname you expect?

**Comment by michthom** [comment]
Not quite what I had in mind. My DDNS domain name is "paddockscottage.synology.me", so if I configure that as a 'permitted' connection, I'd hoped to see something like the following (pseudo code):
```
Connection arrives from IP 'aa.bb.cc.dd'
Configurator checks my pre-configured DDNS hostname(s) with
socket.gethostbyaddr("paddockscottage.synology.me") (repeat for all configured names)
('host81-129-172-73.range81-129.btcentralplus.com', ['73.172.129.81.in-addr.arpa'], ['81.129.172.73'])

If ('81.129.172.73' (or any other configured name resolved address) == 'aa.bb.cc.dd')
    { allow the connection to proceed to authentication }
else
    { error }
```

**Comment by danielperna84** [comment]
Ok, that would work as well. Although it could generate more DNS requests if you whitelist multiple hostnames and the last one happens to be the correct one. But sure, that can be done.

**Comment by michthom** [comment]
It's not high priority since sesame/sesame_totp_secret work pretty well, but it might be even smoother?

**Comment by danielperna84** [comment]
I have implemented this functionality in the [allowed_domains](https://github.com/danielperna84/hass-configurator/tree/allowed_domains) branch. Please test if this is working for you. 👍

**Comment by michthom** [comment]
Hi Daniel
Thanks very much for doing this, I don't want to seem ungrateful but I'm flying to Finland in the morning so may not get a chance to test it for a week or so... 
Based on the code changes it looks pretty solid!
Cheers
Mike

**Comment by michthom** [comment]
Actually - I'm not sure **_how_** to test this, as I'm running currently Configurator as an add-on package to Home Assistant under Hass.io (and I can't see a way to replace with the development branch code)?
I'm presuming I'd need to install Hassbian on another Pi, then manually install your new code using the steps in [this page](https://www.home-assistant.io/docs/ecosystem/hass-configurator/)?

**Comment by danielperna84** [comment]
With hassio it won't be possible to test. You'll need a device with Python 3. Ideally Linux, but Windows with Python 3 works too. Basically you only need the `configurator.py` file. Then fill in your settings and execute it. If it starts up without errors, then you just have to add the port forwarding to the machine where you are running the configurator manually. Don't forget a possible firewall on that machine.

**Comment by michthom** [comment]
Not definitive results as I'm rushing to get to bed, but something may be odd here?

I set up the new script running on my Mac on port 3219, running under:
```
Mike-2017-iMac-1057:hass-configurator michthom$ which python3
/usr/local/bin/python3
Mike-2017-iMac-1057:hass-configurator michthom$ python3 --version
Python 3.7.0
Mike-2017-iMac-1057:hass-configurator michthom$ python3 ./configurator.py 
```
The logs show me connecting from a remote destination (my iPhone) which is not in the allowed networks, and the allowed domains wasn't working yet (neither host nor nslookup were resolving the domain to the IP address) but it let me in anyway, and I could browse files / contents?

This could have been a cached authentication token perhaps, as I'd logged in from the local network previously so as I say not definitive and when I have more time I'll try a more careful test.

```
INFO:2019-02-17 00:03:40,810:__main__:Starting server
INFO:2019-02-17 00:03:40,810:__main__:Listening on: http://0.0.0.0:3219
INFO:2019-02-17 00:03:47,435:__main__:Requesting authorization
INFO:2019-02-17 00:03:47,435:__main__:213.205.198.29 - "GET / HTTP/1.1" 401 -
WARNING:2019-02-17 00:04:52,150:__main__:Client IP not within allowed networks.
INFO:2019-02-17 00:04:52,186:__main__:213.205.198.29 - "GET / HTTP/1.1" 200 -
WARNING:2019-02-17 00:04:52,189:__main__:Exception getting bootstrap
WARNING:2019-02-17 00:04:52,190:__main__:<urlopen error [Errno 61] Connection refused>
WARNING:2019-02-17 00:04:53,656:__main__:Client IP not within allowed networks.
INFO:2019-02-17 00:04:53,657:__main__:213.205.198.29 - "GET /api/listdir?path=. HTTP/1.1" 200 -
INFO:2019-02-17 00:05:25,241:__main__:Requesting authorization
INFO:2019-02-17 00:05:25,241:__main__:213.205.198.29 - "GET /api/listdir?path=. HTTP/1.1" 401 -
INFO:2019-02-17 00:05:30,939:__main__:Requesting authorization
INFO:2019-02-17 00:05:30,939:__main__:213.205.198.29 - "GET / HTTP/1.1" 401 -
WARNING:2019-02-17 00:05:50,315:__main__:Client IP not within allowed networks.
INFO:2019-02-17 00:05:50,316:__main__:213.205.198.29 - "GET / HTTP/1.1" 200 -
WARNING:2019-02-17 00:05:50,316:__main__:Exception getting bootstrap
WARNING:2019-02-17 00:05:50,317:__main__:<urlopen error [Errno 61] Connection refused>
WARNING:2019-02-17 00:05:51,606:__main__:Client IP not within allowed networks.
INFO:2019-02-17 00:05:51,607:__main__:213.205.198.29 - "GET /api/listdir?path=. HTTP/1.1" 200 -
WARNING:2019-02-17 00:05:59,686:__main__:Client IP not within allowed networks.
INFO:2019-02-17 00:05:59,687:__main__:213.205.198.29 - "GET /api/file?filename=/Users/michthom/bin/hass-configurator/changelog.txt HTTP/1.1" 200 -
```

**Comment by danielperna84** [comment]
Don't worry, this has time.
I'm not sure if I understand you correctly. Do you mean you have __not__ added your domain to the list of allowed domains and still were able to login? That shouldn't happen.
If however you have added the domain, then isn't browsing the files what you wanted to do? It only logs an error if domains have been set, and if the client IP does not match any of the resolved domains.

**Comment by michthom** [comment]
Hi Daniel. Yes, the former explanation. I hadn’t (yet) got a working DNS record for the source IP, and the IP address wasn’t in the allowed networks so I expected it to fail.
I did see one attempt that resulted in “policy not fulfilled” so I don’t think it’s a code problem, but I’ll check more carefully on my return.

**Comment by michthom** [comment]
Hi Daniel. My testing seems to have improved after my holiday, and I can replicate a "policy not fulfilled" when the domain name doesn't resolve at all, or doesn't match the incoming request source IP. But when everything lines up, it works just as I'd hoped, thank you.

**Comment by michthom** [comment]
I'm being greedy, I admit, but I was hoping the ALLOWED_DOMAINS would be in the Hass.io add-on v2.1 that was released recently. Should I adjust my aim and wait for the v2.2 to be pushed to the world?

**Comment by danielperna84** [comment]
You have to remove the official add-on and instead add my repository as a source: https://github.com/danielperna84/hassio-addons
The pull request for the official addon has stalled last November, with no signs of being approved anytime soon. So you won't get the new version there. Hence my custom repository.

**Comment by michthom** [comment]
Thanks Daniel for the quick reply. Very odd that the "official" add-on got an update from v2 to v2.1 only in the last few days then? I'll do as you suggest but if there's anything happy users can do to encourage the official add-on pull process (does it need more testers of the development builds?), let us know?

**Comment by danielperna84** [comment]
You probably mean this PR: https://github.com/home-assistant/hassio-addons/pull/538
That only added the `armv7` architecture for existing addons that did not provide it earlier.

The problem with the PR for the updated configurator is, that Pascal wants it to leverage the authentication of Home Assistant instead of using its own. He has prepared something, but probably just is to busy to actually make it work properly. In my opinion the authentication should actually be a separate PR. I don't want to annoy him since he has more important things to do, and for users who really want the latest possible functionality I provide the workaround using my repository.

**Comment by michthom** [comment]
OK, I did find the [0.3.4 PR](https://github.com/home-assistant/hassio-addons/pull/448) and that superficially looked ready to go minus the conflicts, but "Draco Dormiens Nunquam Titillandus" as they say at Hogwarts...

**Comment by danielperna84** [comment]
Actually, the allowed_domains option may not even work in that whole HA-Auth construct he has implemented. It is placing an Nginx webserver in front of the configurator, which acts as a reverse proxy. So from the perspective of the configurator all requests, no matter which external IP, will be coming from the Nginx Server, not the external address.

**Comment by michthom** [comment]
Fair point. In that case perhaps I need to find a polite / appropriate place to suggest Pascal make a similar concession for the Nginx server?

**Comment by danielperna84** [comment]
That would need to be done for every add-on that would use this approach for authentication. Honestly, I think you'll be better off just sticking to my repository. Now that the configurator itself is packaged as a package on pypi I can make it a little more complex and may be able to include the authentication myself instead of putting the Nginx in front. That will take some time and research though.

**Comment by michthom** [comment]
OK, I'm delighted with what you've done already, thanks again.
