### ISSUE TITLE
make a python package published on Pypi.org

### ISSUE THREAD

**Issue by gsemet** [danielperna84/hass-configurator#147]
Hi.

Can you make a python package (setup.py and so) in ordor pip install configuator easily?

Something like:
- pip install hass
- pip intall hass-configurator

and boom the package is installed, and an entrypoint to start/stop the server is provided.

Thanks
Gaetan

**Comment by danielperna84** [comment]
Thought of that myself just yesterday. I'll have a look at it.

**Comment by gsemet** [comment]
I can help you with that :) not that difficult, you can even have travis build automatically your wheel package and upload for you

**Comment by danielperna84** [comment]
I'm already working on it and am almost done. While doing this I'm also including [argparse](https://docs.python.org/3/library/argparse.html) for useful commandline switches.

I don't want to build and push via Travis though. Occasionally contributors point the PRs at the master branch, and when I don't notice that and merge their work, this would publish a new package unintentionally.

**Comment by gsemet** [comment]
You can set your Travisci yaml to publish only on tags :)
See my various python package for example (pipenv_to_requirements, cfgtree and so).

**Comment by danielperna84** [comment]
Package now is available. Try `pip install hass-configurator`. 😉
