### ISSUE TITLE
pip package not available

### ISSUE THREAD

**Issue by Ernst79** [danielperna84/hass-configurator#151]
I've tried to update hass-configurator via pip install hass-configurator, but I get the following error. 

> Could not find a version that satisfies the requirement hass-configurator (from versions: )
> No matching distribution found for hass-configurator

**Comment by danielperna84** [comment]
Uhm, I don't know what the problem might be. It is definetely online: https://pypi.org/project/hass-configurator/
Maybe it's a small detail, but the Configurator is Python 3 only. So depending on your system the correct command may be `pip3 install hass-configurator`.

**Comment by Ernst79** [comment]
Solved it. Had to do it in the virtualenv. 

`sudo su -s /bin/bash homeassistant`
`source /srv/homeassistant/bin/activate`
`pip install hass-configuration`

**Comment by SunsetQuest** [comment]
I had the same issue and @Ernst79 commands and it fixed it.
