### ISSUE TITLE
Core Configurator not working anymore

### ISSUE THREAD

**Issue by otsche1979** [danielperna84/hass-configurator#154]
Hi,
core configurator does not work anymore on 0.91.2.
It says

19-04-09 22:29:44 ERROR (MainThread) [hassio.addons.addon] Add-on core_configurator not supported on raspberrypi3 with ['armv7', 'armhf'] architecture.

Also listed as not usable in Add On View...

Thanks
otsche1979

**Comment by john-arvid** [comment]
I have the same problem when trying to update to 3.1

`ERROR (MainThread) [hassio.addons.addon] Add-on core_configurator not supported on qemux86-64 with ['amd64', 'i386'] architecture`

Also when I unistall the addon and try to install it I only get this in the addon-store: `This addon is not available on your system.`

**Comment by danielperna84** [comment]
Try installing the add-on from my repository: https://github.com/danielperna84/hassio-addons
The _official_ add-on is built for specific target platforms. The version from my repo instead is built locally.

**Comment by palvarez89** [comment]
Can we persuade the _official_ add-on maintainers to provide builds for these targets? Seems really odd to me that it stopped working.

**Comment by danielperna84** [comment]
> Can we persuade the _official_ add-on maintainers to provide builds for these targets? Seems really odd to me that it stopped working.

To get the official add-on fixed please post the issue here: https://github.com/home-assistant/hassio-addons/issues
I'm not involved in building the images. And to me it seems as if the issue here are missing images for specific platforms.

**Comment by palvarez89** [comment]
Opened https://github.com/home-assistant/hassio-addons/issues/565 for the sake of communicating it. It's not helpful to have an *core* addon that cannot be installed in one of the main target devices people will be putting hassio on.

**Comment by john-arvid** [comment]
Just an update, the problem was that home assistant was not updated to minumum version 0.91.1 on the users device.
