### ISSUE TITLE
Addon not working in OpiPrime hassio

### ISSUE THREAD

**Issue by sheminasalam** [danielperna84/hass-configurator#155]
The addon is not working with the following log.
system is OPIPrime running latest hassio and addon

```
[07:27:17] INFO: Add-on running
PANIC: unprotected error in call to Lua API (bad light userdata pointer)
INFO:2019-04-11 07:27:18,317:hass_configurator.configurator:Starting server
INFO:2019-04-11 07:27:18,319:hass_configurator.configurator:Listening on: http://127.0.0.1:80
```

**Comment by danielperna84** [comment]
Please post your issue here: https://github.com/home-assistant/hassio-addons/issues
This repository is for the configurator itself. I'm not responsible for the new add-on.
