### ISSUE TITLE
ignore_pattern config option no longer supported?

### ISSUE THREAD

**Issue by nickdos** [danielperna84/hass-configurator#157]
I'm running hassio (latest) and recently updated to the latest configurator add-on. 

I previously had the config option "ignore_pattern" so I wouldn't have to scroll past all the hidden files in my `config` directory. That no longer seems to work in the latest version. When I try to add it, it doesn't save (I've tried both lowercase and uppercase, according to wiki). The only changes that "stick" are the two default option (changing `true` to `false`).

I checked the docs on this GH repo, which pointed me to the wiki and the docs still talk about this config option so not sure if I'm doing it wrong or the docs are out of date.

**Comment by danielperna84** [comment]
> I checked the docs on this GH repo, which pointed me to the wiki and the docs still talk about this config option so not sure if I'm doing it wrong or the docs are out of date.

This repository is about the application itself (which still has the option you are referring to). The repository for the hassio-addon is here: https://github.com/home-assistant/hassio-addons
There you can file an issue for the missing option. 👍 
There recently has been a big change for the add-on, so in the first run all options where stripped out. They are resurfacing now as users complain about missing options. 😉

**Comment by nickdos** [comment]
For anyone interested, I've filed an issue here: https://github.com/home-assistant/hassio-addons/issues/567
