### ISSUE TITLE
Change UI Background color (non-editor)

### ISSUE THREAD

**Issue by prtene** [danielperna84/hass-configurator#159]
I want to alter the background color of the web UI to match my home assistant theme and I am unsure how to do that. 

The editor itself is easy. I'm referring to outside that where you can select entities. It remains a bright blinding white even when my HA theme is set to a dark one. I'd like them to match when I'm using it.  I'm currently using it with Hass.io

I've attempted some research into it myself but so far am unable to find it's installed location on my hass.io to alter the files themselves.

**Comment by danielperna84** [comment]
It's not possible with hassio. The source-file that contains everything is delivered via a Docker image. And Docker images can't be manipulated efficiently. Additionally, even if you manage to do that, it will revert to the original state with the next update. So there's no other choice but accepting the theme the configurator is delivered with.
