### ISSUE TITLE
Configurator 3.2 addon on HA 0.92.1 openweb UI 502: Bad Gateway

### ISSUE THREAD

**Issue by aanaumkin** [danielperna84/hass-configurator#160]
Configurator 3.2 addon on HA 0.92.1 openweb UI -->502: Bad Gateway

**Comment by aanaumkin** [comment]
Config 
{
  "dirsfirst": false,
  "enforce_basepath": false,
  "ignore_pattern": [
    "__pycache__"
  ]
}
Network
any port

Log
[17:54:37] INFO: Add-on running
PANIC: unprotected error in call to Lua API (bad light userdata pointer)
INFO:2019-05-01 17:54:38,237:hass_configurator.configurator:Starting server
INFO:2019-05-01 17:54:38,239:hass_configurator.configurator:Listening on: http://127.0.0.1:80

SYSTEM LOG
19-05-01 13:42:40 INFO (MainThread) [hassio.addons.addon] Create Home Assistant add-on data folder /data/addons/data/core_configurator
19-05-01 13:42:40 INFO (SyncWorker_9) [hassio.docker.interface] Pull image homeassistant/aarch64-addon-configurator tag 3.2.
19-05-01 13:42:52 INFO (SyncWorker_9) [hassio.docker.interface] Tag image homeassistant/aarch64-addon-configurator with version 3.2 as latest
19-05-01 13:43:51 INFO (SyncWorker_0) [hassio.docker.addon] Start Docker add-on homeassistant/aarch64-addon-configurator with version 3.2
19-05-01 13:43:55 ERROR (MainThread) [hassio.api.ingress] Ingress error: Cannot connect to host 172.30.33.0:8099 ssl:None [Connection refused]
19-05-01 13:44:22 ERROR (MainThread) [hassio.api.ingress] Ingress error: Cannot connect to host 172.30.33.0:8099 ssl:None [Connection refused]
19-05-01 13:45:00 ERROR (MainThread) [hassio.api.ingress] Ingress error: Cannot connect to host 172.30.33.0:8099 ssl:None [Connection refused]
19-05-01 13:45:21 ERROR (MainThread) [hassio.api.ingress] Ingress error: Cannot connect to host 172.30.33.0:8099 ssl:None [Connection refused]
19-05-01 13:54:05 ERROR (MainThread) [hassio.api.ingress] Ingress error: Cannot connect to host 172.30.33.0:8099 ssl:None [Connection refused]
19-05-01 13:54:33 INFO (SyncWorker_4) [hassio.docker.interface] Stop addon_core_configurator application
19-05-01 13:54:34 INFO (SyncWorker_4) [hassio.docker.interface] Clean addon_core_configurator application
19-05-01 13:54:36 INFO (SyncWorker_9) [hassio.docker.addon] Start Docker add-on homeassistant/aarch64-addon-configurator with version 3.2
19-05-01 13:54:37 ERROR (MainThread) [hassio.api.ingress] Ingress error: Cannot connect to host 172.30.33.0:8099 ssl:None [Connection refused]
19-05-01 14:12:40 ERROR (MainThread) [hassio.api.ingress] Ingress error: Cannot connect to host 172.30.33.0:8099 ssl:None [Connection refused]
19-05-01 14:14:11 ERROR (MainThread) [hassio.api.ingress] Ingress error: Cannot connect to host 172.30.33.0:8099 ssl:None [Connection refused]
19-05-01 14:14:44 ERROR (MainThread) [hassio.api.ingress] Ingress error: Cannot connect to host 172.30.33.0:8099 ssl:None [Connection refused]
19-05-01 14:18:11 ERROR (MainThread) [hassio.api.ingress] Ingress error: Cannot connect to host 172.30.33.0:8099 ssl:None [Connection refused]
19-05-01 14:34:32 ERROR (MainThread) [hassio.api.ingress] Ingress error: Cannot connect to host 172.30.33.0:8099 ssl:None [Connection refused]
19-05-01 14:38:29 ERROR (MainThread) [hassio.api.ingress] Ingress error: Cannot connect to host 172.30.33.0:8099 ssl:None [Connection refused]

**Comment by aanaumkin** [comment]
Please give advice.
Thank you in advance.

**Comment by danielperna84** [comment]
This repository is only about the application itself, not the hassio add-on.
Please head over to the community at https://community.home-assistant.io
There are numerous threads about the configurator add-on that may already solve your problem. If not, there will be people that can assist you with finding a solution.
