### ISSUE TITLE
401: Unauthorized

### ISSUE THREAD

**Issue by sanderlv** [danielperna84/hass-configurator#161]
Having HASSio latest version. 
Configurator add-on installed and "green":
Show in sidebar on-off does not change antything.
Configurator is visible in left sidebar in hassio. Link location is: http**s**://hassio-ip:8123/core_configurator. When clicking on it it shows: 401: Unauthorized.

I can only go to configurator if I change the port in add-on configuration to 3218 and go to link http://hassio-ip:3218/ 

What is not working to go via the menu? https vs http? Other?

**Comment by danielperna84** [comment]
Please head over to the forum. This repository is not the correct place for support. In the forum plenty of others users who may be able to help are around.
