### ISSUE TITLE
Feature Request: Rename file

### ISSUE THREAD

**Issue by MarcHagen** [danielperna84/hass-configurator#162]
Hi there, 
Love the plugin/addon/script. The only thing i'm really missing is a rename file option.
It would be great if that can be added just above the file delete button.

Also small bug is that the button is not full width:
![image](https://user-images.githubusercontent.com/980978/63053547-428e0200-bee2-11e9-8fbe-2402c6236ac3.png)
And i think you have the classes on the wrong item.
https://github.com/danielperna84/hass-configurator/blob/c74c8f8f57352e3de3fb5e0d24e640919db26871/hass_configurator/configurator.py#L2611-L2613

Should be this to be inline with the download button:
```
        var dd_delete = document.createElement('li');
        var dd_delete_a = document.createElement('a');
        dd_delete_a.classList.add("waves-effect", "fb_dd");
```

**Comment by danielperna84** [comment]
Thanks for the hint regarding the button.

As for your request, I'll get it into the next version. I've been very busy recently, and for the update from today I just focued on dependency updates and things that were easy to do. Renaming will require some work in the UI and API in the backend. But as a workaround you obviously can simply create new files and copy the content from one to the other until I'm done. 👍

**Comment by danielperna84** [comment]
I have added the functionality now in the devel-branch. So it definetly will be in the next version. 👍
