### ISSUE TITLE
Feature request: hide files beginning with .

### ISSUE THREAD

**Issue by gregschwartz** [danielperna84/hass-configurator#165]
<img width="1149" alt="Screen Shot 2019-09-28 at 8 30 42 PM" src="https://user-images.githubusercontent.com/206568/65825710-ffd47f00-e22e-11e9-8e66-fc62163a4987.png">

Other editors I've used have added some ._FILENAME files. And there are also hidden config files that start with . (e.g. `.storage`). Would be great to have those hidden, or at least a toggle  (on by default) to hide them.

Thanks!

**Comment by danielperna84** [comment]
There now is a global setting for this: [HIDEHIDDEN](https://github.com/danielperna84/hass-configurator/wiki/Configuration#hidehidden-bool)
