### ISSUE TITLE
Feature request: add buttons for Check Config and Restart Server

### ISSUE THREAD

**Issue by gregschwartz** [danielperna84/hass-configurator#166]
After a file has been saved, show a `Check Config` button: 
<img width="1139" alt="Screen Shot 2019-09-28 at 8 43 48 PM" src="https://user-images.githubusercontent.com/206568/65825853-c8ff6880-e230-11e9-98c1-00fed544ff49.png">

If it doesn't pass, show errors on both the appropriate lines, and in a pop-up panel.

If that passes, then show a `Restart Server` button:
<img width="1139" alt="Screen Shot 2019-09-28 at 8 47 33 PM" src="https://user-images.githubusercontent.com/206568/65825888-488d3780-e231-11e9-9f1d-1d5a96e6cf7b.png">

Would be a big help, so we wouldn't have to keep switching between a tab with the Configurator, and a tab with the Server Controls.

**Comment by danielperna84** [comment]
Since Home Assistant is approaching version 1.0 I will not implement this, because eventually the configurator will become obsolete.  
The current yaml-linting (green checkmark on the upper right) already gives you a hint if there are general syntax errors. And via the gear symbol on the right you already have an option to restart the server.  
So even though I do see the benefit, I don't feel it's worth the effort. Of course you are free to give it a shot to implement it yourself and create a pull request so I can merge it into this project. 👍

**Comment by Misiu** [comment]
@danielperna84 so You don't plan to add new features into Configurator?
I've created an issue in hassio-addons about offline usage - https://github.com/home-assistant/hassio-addons/issues/760.
A couple of minutes ago I found Your repo and I was thinking about creating an issue here. Do you plan to stop the development of Configurator? It's the first add-on people install, I'd say it's a "must-have" add-on :)

**Comment by danielperna84** [comment]
No, I don't want to stop development. But restarting is already possible, and the easy workaround to check the configuration is to have another open tab with Home Assistant. So essentially what's asked for in this request is already possible, just not as streamlined within the configurator.  
I atually already had checking the configuration implemented once (it just showed the result in a modal though). But the API changed on the HASS side, so I dropped the support.  
If someone wants to take care of this I'm open for it. But I've been very busy recently, and that won't change for a while. Hence I don't want to implement something that's already possible as a workaround. Other issues might be worked around too (renaming files), but they also give value without being related to Home Assistant. So I prioritize those issues differently.
