### ISSUE TITLE
Feature request: add option to always show file explorer

### ISSUE THREAD

**Issue by Tediore** [danielperna84/hass-configurator#168]
To be used in conjunction with the new option in the Hassio addon to toggle the HASS panel.

**Comment by danielperna84** [comment]
That's not possible with the current architecture and would require significant changes with a great chance of breaking the layout for everything else. As you might have noticed, the editor area gets dimmed when the file explorer is visible. So even if clicking outside the explorer wouldn't hide it, the editor still would be (partially) covered by the filebrowser.

**Comment by Tediore** [comment]
Understood, thanks for the response!
