### ISSUE TITLE
Login attempt or request with invalid authentication from 127.0.0.1

### ISSUE THREAD

**Issue by tms320** [danielperna84/hass-configurator#173]
I have installed Home Assistant (HA) as docker container using the following instruction:
https://www.home-assistant.io/docs/installation/docker/
My HA configuration directory is mapped from docker container to host directory '/home/pi/homeassistant'.
Then, I installed HASS Configurator (v.0.3.6) using standalone legacy installation.
It works. But each time I open Configurator (from HA UI) I get notification:
_Login attempt or request with invalid authentication from 127.0.0.1_
Then I tried to setup Configurator to use HASS API:
I added to 'configuration.yaml' the following config:
```
homeassistant:
  auth_providers:
    - type: legacy_api_password
      api_password: !secret http_api_password
```
I added to 'secrets.yaml':
`http_api_password: MY_PASSWORD`

I edited 'configurator.py':
```
BASEPATH = "/home/pi/homeassistant/"
HASS_API = "http://127.0.0.1:8123/api/"
HASS_API_PASSWORD = "MY_PASSWORD"
USERNAME = None
PASSWORD = None
```
But I am still getting the same notification.
Besides, HASS API doesn't work from Configurator: I press 'Restart HASS' but HA not restarted.

**Comment by danielperna84** [comment]
You have to use a [long-lived access token](https://developers.home-assistant.io/docs/en/auth_api.html#long-lived-access-token), which you can create on your [profile](https://www.home-assistant.io/docs/authentication/#your-account-profile). API tokens have been deprecated for a while. The name of the setting in the configurator just didn't change for backwards compatibility.

**Comment by tjunussov** [comment]
Sorry, but in wiki configuration page it is written:

**Both the old fashioned api_password** and the new long-lived access tokens

> If you plan on using API functions (reloading stuff, fetching entities and services etc.), you have to set your API password. Calling the API of Home Assistant is prohibited without authentication. Both the old fashioned api_password and the new long-lived access tokens (you can create those on your profile page at http://your-hass-address.com/profile) are supported.

may be we should correct this in wiki ?
