### ISSUE TITLE
Configurator not show up correct

### ISSUE THREAD

**Issue by joselito11** [danielperna84/hass-configurator#176]
Configurator not show up correct. The problem persist few motnhs. Tried to uninstall, reboot HA, and fresh install. I really want to use it, but it only work on HA iOS iPhone. No Mac, no iPad, no Safari, no Debian, no Ubuntu, no Chrome, no Chromium, no Firefox,... Please help.
Screenshot: https://imgur.com/a/rfLBjxz

**Comment by danielperna84** [comment]
Your browser seems to fail at loading external resources (CSS and JavaScript). The most common cause of such problems are products like PiHole that block traffic to certain destinations.

**Comment by joselito11** [comment]
It was PiHole. Sorry for this. Thank you!
