### ISSUE TITLE
Domain + HTTPS + local Configurator

### ISSUE THREAD

**Issue by NewFolk** [danielperna84/hass-configurator#179]
Hello,

Thank you for this cool project. It makes home assistant configuration very easy for beginners.
But I stacked with the problem and it looks to me that there is no solution.

I have the following setup: 
Home Assistant in docker
Standalone HASS configurator in docker
External access to Home Assistant https://ha.example.com through nginx.
And local Configurator on http://192.168.1.2

If everything understood correctly, there is no possibility to integrate Configurator to panel_iframe?
Until I setup external access to Configurator ( https://configurator.example.com )

**Comment by danielperna84** [comment]
You can integrate it as a panel_frame. But from outside of your network the address `192.168.1.2` won't be resolved and the configurator wouldn't work. So yes, you have to expose the configurator to make it accessible somehow. The recommended solution would be to use a [reverse proxy](https://en.wikipedia.org/wiki/Reverse_proxy) (Apache or NGINX are popular choices).

**Comment by NewFolk** [comment]
Thank you
