### ISSUE TITLE
hass_configurator.configurator:Access denied

### ISSUE THREAD

**Issue by djmalin** [danielperna84/hass-configurator#180]
hello, I have a request how can I get rid of this error, I can not exit config, but I can be in this directory:
INFO:2020-01-14 18:19:51,345:hass_configurator.configurator:Starting server
INFO:2020-01-14 18:19:51,363:hass_configurator.configurator:Listening on: http://0.0.0.0:8099
INFO:2020-01-14 18:20:51,909:hass_configurator.configurator:172.30.32.2 - "GET / HTTP/1.1" 200 -
INFO:2020-01-14 18:20:55,225:hass_configurator.configurator:172.30.32.2 - "GET /api/file?filename=/config/scripts.yaml HTTP/1.1" 200 -
INFO:2020-01-14 18:20:55,688:hass_configurator.configurator:172.30.32.2 - "GET /api/listdir?path=. HTTP/1.1" 200 -
INFO:2020-01-14 18:21:00,573:hass_configurator.configurator:172.30.32.2 - "GET /api/listdir?path=/ HTTP/1.1" 200 -
WARNING:2020-01-14 18:21:00,574:hass_configurator.configurator:Access denied.

# This it __NOT__ a support channel for problems with the HASS Configurator hassio add-on!
If you need assistance, please head over to the forum at https://community.home-assistant.io or the [Discord](https://discord.gg/c5DvZ4e) chat.

If you think you have found a bug, please post which version of the HASS Configurator you are using and how to reproduce the bug and in which environment you encounter the problem (Browser, Installation type etc.).

If you feel the HASS Configurator lacks a useful feature, just describe what that would be. You may also try to implement it yourself and create a pull request so your work can be merged into this project.

**Comment by danielperna84** [comment]
Please rephrase your question. I don't understand the problem. _Access denied_ happens when you try to navigate to a folder you are not allowed to access. So just don't try to go there.

**Comment by djmalin** [comment]
ok, problem solved, I changed the settings

"dirsfirst": true,
  "enforce_basepath": false,
