### ISSUE TITLE
Rename HASS references to Home Assistant

### ISSUE THREAD

**Issue by Kisty** [danielperna84/hass-configurator#181]
With the recent renames of:
HASS ➡ Home Assistant 
Home Assistant ➡ Home Assistant Core

Would it be worth thinking about renaming 'Restart HASS' to 'Restart Home Assistant'? I realise that there's a transitioning period, but would be good to be ahead of the game.

Configurator: 0.3.7
Home Assistant Core: 0.104.3

https://www.home-assistant.io/blog/2020/01/29/changing-the-home-assistant-brand/

**Comment by danielperna84** [comment]
> HASS ➡ Home Assistant

That's actually not correct. It's hass.io ➡ Home Assistant. The Configurator however works both with hass.io and Home Assistant. Or Home Assistant and Home Assistant Core. It's agnostic of what infrastructure is used. So calling it Home Assistant would let Home Assistant Core users think it wouldn't work form them. Or the other way araound. So I prefer to stay with the much shorter HASS, which could be both of the systems I guess.

**Comment by Kisty** [comment]
Fair enough. 

Yeah, I missed the '.io' bit but you refer to it as HASS so used your naming.
