### ISSUE TITLE
Missing addons folder

### ISSUE THREAD

**Issue by Romkabouter** [danielperna84/hass-configurator#182]
Hi there,

I seem to miss the addons folder in the left explorer bar. All the other folders (share/ssl/backup/config) are there.
Is this an issue or am I missing something?

**Comment by danielperna84** [comment]
The explorer displays everything it can find at the set path. If a specific folder seems to be missing, then it is either not available at the searched path, or it has permissions that prevent the configurator from reading it. In any case, the source of the problem should not be the configurator. It doesn't just hide elements.

**Comment by Romkabouter** [comment]
After some more searching I have your reply on this topic:
https://community.home-assistant.io/t/can-i-access-the-addon-folder-with-the-configurator/60157/2

I feel it is still a good idea to map it into the container though.
