### ISSUE TITLE
Login attempt failed

### ISSUE THREAD

**Issue by davidsuarez82** [danielperna84/hass-configurator#184]
Hi, I'm getting a notification every time I open the configurator. It asks for user and password and then opens but the notification still appears.

**Comment by danielperna84** [comment]
Could you be a little more precise? Where do you get the notification? And what exactly does it say? Do you have a standalone installation or are you using the hassio-addon? The text you have deleted while creating this issue asked for such details. Without them I can't help.

**Comment by davidsuarez82** [comment]
Hi, 

The error is showing in the Home Assistant Notifications, I run a home assistant (not Hass.io) installation in docker.

I took a screenshot before and one after login

before: https://i.imgur.com/vXSiMQb.png

after: https://i.imgur.com/5UGHGIx.png

Regards,

**Comment by danielperna84** [comment]
The message is a result of misconfiguration. Home Assistant rejects the configurators requests about the entities, services etc.. Please verify that your [HASS_API_PASSWORD](https://github.com/danielperna84/hass-configurator/wiki/Configuration#hass_api_password-string) is correct.
