### ISSUE TITLE
Hass.io Configurator Core add-on reverted.

### ISSUE THREAD

**Issue by frenck** [danielperna84/hass-configurator#187]
I've just reverted the latest release of the hass-configurator inside the core add-on: <https://github.com/home-assistant/hassio-addons/pull/1094>

Issues reported with the latest version:

- <https://github.com/home-assistant/hassio-addons/issues/1093>
- <https://github.com/home-assistant/hassio-addons/issues/1092>
- <https://github.com/home-assistant/hassio-addons/issues/1095>
- <https://github.com/home-assistant/hassio-addons/issues/1096>

**Comment by danielperna84** [comment]
The offline-files are missing in the `MANIFEST.in` file. Didn't notice it since in my dev-environment they were present. Will fix that later today.
