### ISSUE TITLE
File Editor caracters are shifted form cursor

### ISSUE THREAD

**Issue by guiguid** [danielperna84/hass-configurator#197]
Hi,
With the 5.0 update of the File Editor Addons, I've a 5/6 caracter shift with the cursor !

![HA-FileEditor5 0-caracterbug](https://user-images.githubusercontent.com/71406/80712625-823d5e00-8af2-11ea-8173-10652b0ab801.gif)

This strange bug isn't présent in previous release.
It's fonts related ?

Tested with : 
Firefox 75, with -safe-mode + cache cleaning on linux manjaro 20 
Chromium Version 81.0.4044.122 on linux manjaro 20

HA : 0.109.1
File editor : 5.0.0

arch  | x86_64
dev | false
docker | true
hassio | true
os_name | Linux
os_version | 5.6.5-3-MANJARO
python_version | 3.7.7
timezone | Europe/Paris
version | 0.109.1
virtualenv | false

I've uninstall and reinstall File editor addon with no succes. 

Link Issue : https://github.com/home-assistant/hassio-addons/issues/1261

**Comment by itsyoshio** [comment]
+1

**Comment by danielperna84** [comment]
I can't reproduce this problem with a standalone-installation. Does this only apply to certain filetypes?

**Comment by itsyoshio** [comment]
It happens in the core_configurator addon aswell as in esphome (all installed via hassos supervisor) and any other place this editor is used.

https://user-images.githubusercontent.com/12760988/103536318-97913600-4e92-11eb-8417-f31d3c2735cb.mp4

Doesn't matter wheather i'm on my instance or on a friends (different network, host, instance) so it is related to my Notebook.
I tried Hard Reloading but not no avail.

I'm on Manjaro with GNOME Shell 3.38.2 on Wayland and Chromium 87.0.4280.88 (Official Build) Arch Linux (64-bit)

**Comment by danielperna84** [comment]
What I meant by _standalone_ is installing the HASS-Configurator application itself without any container. Since you are on Linux, please try the following:

```bash
cd /tmp
python3 -m venv venv
source venv/bin/activate
pip install hass_configurator
# This will install the HASS-Configurator application within the temporary virtual environment
# Then start with
hass-configurator
# The output will be something like:
INFO:2021-01-04 22:57:00,382:hass_configurator.configurator:Starting server
INFO:2021-01-04 22:57:00,383:hass_configurator.configurator:Listening on: http://0.0.0.0:3218
```
You should then be able to point your browser at http://127.0.0.1:3218 and get the configurator. This is a plain installation, and I now have done this multiple times on different machines and never got the problem you are reporting. So from my point of view, this is __not__ a problem with the application.
