### ISSUE TITLE
Check config / File Configurator does not flag duplicate sections

### ISSUE THREAD

**Issue by hampshire-al** [danielperna84/hass-configurator#198]
I've just reported this issue in the wrong area - please see: home-assistant/core#35493

The issue I have is that the Android app spots duplicate sections in configuration.yaml - in my case I had duplicated the "sensor:" section to include two different devices - but the main File Configurator does not seem to spot this and it would be helpful to relative beginners (me!!) to replicate this behaviour in the Configurator.

While I now understand from Frenck that the YAML is not technically wrong as duplicate sections are allowed for overrides, etc., it caused an issue in my case as my sensors disappeared as a result of the duplication.

Finding the problem would not have been obvious to me had I not seen the issue flagged in the Android app.

Could this be checking behaviour be considered/fixed in Configurator? 
Is it supposed to happen anyway?

Thanks.

**Comment by danielperna84** [comment]
The configurator does not have the same level of access to the config-checking mechanism that Home Assistant itself has. And there's no straightforward way to ask Home Assistant if the configuration is valid. We can just check if the syntax is correct. But that doesn't include duplicate sections. Hence this feature won't / can't be implemented.
