### ISSUE TITLE
Not starting, looks like "broken web page"

### ISSUE THREAD

**Issue by PsyonicOne** [danielperna84/hass-configurator#200]
# This it __NOT__ a support channel for problems with the HASS Configurator hassio add-on!
If you need assistance, please head over to the forum at https://community.home-assistant.io or the [Discord](https://discord.gg/c5DvZ4e) chat.

If you think you have found a bug, please post which version of the HASS Configurator you are using and how to reproduce the bug and in which environment you encounter the problem (Browser, Installation type etc.).

If you feel the HASS Configurator lacks a useful feature, just describe what that would be. You may also try to implement it yourself and create a pull request so your work can be merged into this project.

About 2 weeks ago, HASS Configurator began not loading and only showing as a LONG list of text, like in pic. Someone said it "looks like a CSS mishap" (whatever that means)
Anyway, I've tried several times to reinstall it, I've cleared my browser cache, I've tried the web interface on 3 different browsers, 2 different OS's, and it is even the same in the HA Android app, all have the same problem.
Version is 5.0.0
I'm running latest HA in a Linux Docker on Pi4

HA log shows this:
20-08-01 10:06:24 INFO (MainThread) [supervisor.ingress] Update Ingress as panel for core_configurator

HASS Configurator log is:
6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
INFO:2020-07-30 21:46:26,500:hass_configurator.configurator:Starting server
INFO:2020-07-30 21:46:26,502:hass_configurator.configurator:Listening on: http://0.0.0.0:8099
INFO:2020-07-30 21:46:27,652:hass_configurator.configurator:172.30.32.2 - "GET / HTTP/1.1" 200 -
INFO:2020-07-30 21:46:28,141:hass_configurator.configurator:172.30.32.2 - "GET /material-icons.fallback.css HTTP/1.1" 200 -
INFO:2020-07-30 21:46:28,164:hass_configurator.configurator:172.30.32.2 - "GET /style.css HTTP/1.1" 200 -
INFO:2020-07-30 21:46:28,217:hass_configurator.configurator:172.30.32.2 - "GET /jquery-3.4.1.min.js HTTP/1.1" 200 -
INFO:2020-07-30 21:46:28,218:hass_configurator.configurator:172.30.32.2 - "GET /materialize.min.js HTTP/1.1" 200 -
INFO:2020-07-30 21:46:28,221:hass_configurator.configurator:172.30.32.2 - "GET /js-yaml.min.js HTTP/1.1" 200 -
INFO:2020-07-30 21:46:28,454:hass_configurator.configurator:172.30.32.2 - "GET /flUhRq6tzZclQEJ-Vdg-IuiaDsNc.woff2 HTTP/1.1" 200 -
INFO:2020-07-30 21:46:28,665:hass_configurator.configurator:172.30.32.2 - "GET /api/listdir?path=. HTTP/1.1" 200 -
INFO:2020-07-31 12:51:54,396:hass_configurator.configurator:172.30.32.2 - "GET / HTTP/1.1" 200 -
INFO:2020-07-31 12:51:55,025:hass_configurator.configurator:172.30.32.2 - "GET /material-icons.fallback.css HTTP/1.1" 200 -
INFO:2020-07-31 12:51:55,027:hass_configurator.configurator:172.30.32.2 - "GET /style.css HTTP/1.1" 200 -
INFO:2020-07-31 12:51:55,116:hass_configurator.configurator:172.30.32.2 - "GET /jquery-3.4.1.min.js HTTP/1.1" 200 -
INFO:2020-07-31 12:51:55,119:hass_configurator.configurator:172.30.32.2 - "GET /materialize.min.js HTTP/1.1" 200 -
INFO:2020-07-31 12:51:55,201:hass_configurator.configurator:172.30.32.2 - "GET /flUhRq6tzZclQEJ-Vdg-IuiaDsNc.woff2 HTTP/1.1" 200 -
INFO:2020-07-31 12:51:55,322:hass_configurator.configurator:172.30.32.2 - "GET /js-yaml.min.js HTTP/1.1" 200 -
INFO:2020-07-31 12:51:56,796:hass_configurator.configurator:172.30.32.2 - "GET /api/listdir?path=. HTTP/1.1" 200 -
INFO:2020-08-01 20:06:26,949:hass_configurator.configurator:172.30.32.2 - "GET / HTTP/1.1" 200 -
INFO:2020-08-01 20:06:27,509:hass_configurator.configurator:172.30.32.2 - "GET /material-icons.fallback.css HTTP/1.1" 200 -
INFO:2020-08-01 20:06:27,514:hass_configurator.configurator:172.30.32.2 - "GET /style.css HTTP/1.1" 200 -
INFO:2020-08-01 20:06:27,537:hass_configurator.configurator:172.30.32.2 - "GET /jquery-3.4.1.min.js HTTP/1.1" 200 -
INFO:2020-08-01 20:06:27,539:hass_configurator.configurator:172.30.32.2 - "GET /materialize.min.js HTTP/1.1" 200 -
INFO:2020-08-01 20:06:27,542:hass_configurator.configurator:172.30.32.2 - "GET /js-yaml.min.js HTTP/1.1" 200 -
INFO:2020-08-01 20:06:27,647:hass_configurator.configurator:172.30.32.2 - "GET /flUhRq6tzZclQEJ-Vdg-IuiaDsNc.woff2 HTTP/1.1" 200 -
INFO:2020-08-01 20:06:27,881:hass_configurator.configurator:172.30.32.2 - "GET /api/listdir?path=. HTTP/1.1" 200 -

![fileEditor](https://user-images.githubusercontent.com/46242800/89099538-6c15a580-d433-11ea-9b9e-9a31d325c9d9.png)

**Comment by danielperna84** [comment]
You either have some browser extension that's blocking the loading of externally hosted content that is required, or you have added something like pi-hole to your network which would prevent your browser from accessing these external resources as well. In case this should be accessible from outside of your home network, try accessing it it externally (like turning off wifi on your phone). It should start working again.

**Comment by PsyonicOne** [comment]
Thanks @danielperna84 
I do have a pi-hole so checked that out. The only thing it was blocking when I loaded Configurator was cdnjs.cloudflare.com
I whitelisted it and it started working again, re-blacklisted it and Configurator is still working. Whatever it was is good now!
Thanks for your help!

**Comment by danielperna84** [comment]
> I whitelisted it and it started working again, re-blacklisted it and Configurator is still working.

Probably because of caching. So expect the problem to surface again. But at least now you know the solution.

**Comment by nickidw** [comment]
I had the same issue until today, Brave console reported a TLS cypher issue to the cloudflare url 2 comments above.
