### ISSUE TITLE
add files to .gitignore

### ISSUE THREAD

**Issue by jmgiaever** [danielperna84/hass-configurator#204]
![Screenshot from 2020-09-16 00-48-04](https://user-images.githubusercontent.com/7188121/93272677-4f041e80-f7b6-11ea-8da3-7431d17c7414.png)

it would be neat if there's an option to add files to the «git ignore», e.g the `secret.yaml` file. I would love to share my HA config :)

**Comment by danielperna84** [comment]
You should be able to open the `.gitignore` file using the configurator and add any files you want that way. That's what the configurator is made for. The other git-related options are just there because that can't be done just by manipulating text files.

**Comment by jmgiaever** [comment]
1. Seems like HC is hiding dot-files by default?
2. Hide dot-files is preferred through the web UI

My intention of using  the configurator is to avoid logging in through SSH to do edits.

**Comment by danielperna84** [comment]
There are the options [IGNORE_PATTERN](https://github.com/danielperna84/hass-configurator/wiki/Configuration#ignore_pattern-list) and [HIDEHIDDEN](https://github.com/danielperna84/hass-configurator/wiki/Configuration#hidehidden-bool). If you adjust those correctly it's easy to modify the gitignore-file. No need to use SSH. 🤷‍♂️
