### ISSUE TITLE
Client IP banned.

### ISSUE THREAD

**Issue by vetmiker** [danielperna84/hass-configurator#205]
I'm not able to open the File editor frame in Home Assistant:
![file_editor_error](https://user-images.githubusercontent.com/4014108/96180651-5f640200-0ef8-11eb-81ce-2a82a367299a.png)

Here is what I see in the log:

`INFO:2020-10-15 13:43:39,313:hass_configurator.configurator:Listening on: http://0.0.0.0:8099
WARNING:2020-10-15 13:43:40,940:hass_configurator.configurator:Client IP not within allowed networks.
INFO:2020-10-15 13:43:40,940:hass_configurator.configurator:172.30.32.1 - "GET / HTTP/1.1" 420 -
WARNING:2020-10-15 13:45:22,725:hass_configurator.configurator:Client IP banned.
INFO:2020-10-15 13:45:22,725:hass_configurator.configurator:172.30.32.1 - "GET / HTTP/1.1" 420 -`

I do not have a  `ip_bans.yaml` file in my config directory. I tried adding trusted network to configuration.yaml:
![config](https://user-images.githubusercontent.com/4014108/96181013-ed3fed00-0ef8-11eb-9fe4-0747cbec0347.png)

Adding the trusted network didn't change behavior.

Here is my config:
* Supervised install on Rasperry OS 10 (buster)
* Also have raspap installed on the Pi. Here is background on what it changed: https://github.com/billz/raspap-webgui/wiki/Manual-installation

**Comment by danielperna84** [comment]
The configurator has its own mechanism to block IPs from unknown networks: https://github.com/danielperna84/hass-configurator/wiki/Configuration#allowed_networks-list
That being said, I don't maintain the add-on variant of the configurator and don't know details about the configuration. Hence if the link about the setting does not help, please post your question in the community forum. I bet there you'll find users which might be able to help you. 👍
