### ISSUE TITLE
Add support for new keywords introduced with the new 'blueprints'

### ISSUE THREAD

**Issue by jmgiaever** [danielperna84/hass-configurator#207]
Hi,

With the new version on HA (2020.12.0) there's introduced new keywords with the new integration `blueprints`. One of them that I know of is `!input`.

![Screenshot from 2020-12-15 00-17-58](https://user-images.githubusercontent.com/7188121/102147605-4e3d6000-3e6b-11eb-9553-22ae7a2a34be.png)

**Comment by martinw72** [comment]
yes, would be great! I'm using Editor to adapt blueprints and make new once, but can't check them for real issues if the !input is not reconized right!
