### ISSUE TITLE
Cannot install hass-configurator addon

### ISSUE THREAD

**Issue by DrKatozzo** [danielperna84/hass-configurator#212]
Hello,
I have been using this addon for a long time. I prefer it to the official one because of the possibility to access the editor without going through the Home assistant interface.
Yesterday unfortunately I had to change the sd card and I noticed that I can no longer install the addon, not even trying to restore a backup.
I'm using Home Assistant OS.
Core Version core-2021.4.4
Supervisor Version supervisor-2021.03.9
On a Raspberry pi4
Thanks!
Max

Below is the log.

21-04-13 06:08:13 ERROR (SyncWorker_0) [supervisor.docker.addon] Can't build b794684e/aarch64-addon-configurator_latest:0.4.0: The command '/bin/ash -o pipefail -c apk add --no-cache python3 git curl openssh   && pip3 install GitPython   && pip3 install pyotp   && curl -s -o /configurator.py https://raw.githubusercontent.com/danielperna84/hass-configurator/$CONFIGURATOR_VERSION/configurator.py   && apk del curl' returned a non-zero code: 127
21-04-13 06:08:13 ERROR (SyncWorker_0) [supervisor.docker.addon] Build log: 
Step 1/14 : ARG BUILD_FROM
Step 2/14 : FROM $BUILD_FROM
 ---> f7f546c71607
Step 3/14 : ENV LANG C.UTF-8
 ---> Using cache
 ---> c9277c993301
Step 4/14 : ARG CONFIGURATOR_VERSION
 ---> Using cache
 ---> 170e6131301b
Step 5/14 : RUN apk add --no-cache python3 git curl openssh   && pip3 install GitPython   && pip3 install pyotp   && curl -s -o /configurator.py https://raw.githubusercontent.com/danielperna84/hass-configurator/$CONFIGURATOR_VERSION/configurator.py   && apk del curl
 ---> Running in f9867a159d9a
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/aarch64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/aarch64/APKINDEX.tar.gz
(1/15) Installing expat (2.2.10-r1)
(2/15) Installing pcre2 (10.36-r0)
(3/15) Installing git (2.30.2-r0)
(4/15) Installing openssh-keygen (8.4_p1-r3)
(5/15) Installing libedit (20191231.3.1-r1)
(6/15) Installing openssh-client (8.4_p1-r3)
(7/15) Installing openssh-sftp-server (8.4_p1-r3)
(8/15) Installing openssh-server-common (8.4_p1-r3)
(9/15) Installing openssh-server (8.4_p1-r3)
(10/15) Installing openssh (8.4_p1-r3)
(11/15) Installing libbz2 (1.0.8-r1)
(12/15) Installing libffi (3.3-r2)
(13/15) Installing gdbm (1.19-r0)
(14/15) Installing sqlite-libs (3.34.1-r0)
(15/15) Installing python3 (3.8.8-r0)
Executing busybox-1.32.1-r3.trigger
OK: 90 MiB in 58 packages
/bin/ash: pip3: not found

Removing intermediate container f9867a159d9a

**Comment by danielperna84** [comment]
This is not the repository of the add-on. That would be [here](https://github.com/danielperna84/hassio-addons) I guess. But that's not maintained anymore. There probably have been some changes in Home Assistant which make that incompatible.

I don't know if using the [Docker](https://github.com/danielperna84/hassio-addons) distribution can be helpful. If that doesn't work, then there's no alternative to the official add-on (which I am not the maintainer of).

Sorry for the bad news. 😕

**Comment by DrKatozzo** [comment]
Hi Daniel, thank you for your reply!
Have a nice day!
