### ISSUE TITLE
Unable to copy/paste in Home Assistant Companion

### ISSUE THREAD

**Issue by antoweb** [danielperna84/hass-configurator#214]
# This it __NOT__ a support channel for problems with the HASS Configurator hassio add-on!
If you need assistance, please head over to the forum at https://community.home-assistant.io or the [Discord](https://discord.gg/c5DvZ4e) chat.

Version 5.3.0
Usng the addon in Home Assistant companion is impossible to copy and paste

**Comment by danielperna84** [comment]
This is already mentioned in issue #27. This probably won't be fixed any time soon.
