### ISSUE TITLE
Can't set BASEPATH

### ISSUE THREAD

**Issue by timothybuchanan** [danielperna84/hass-configurator#220]
I pulled configurator using this command:
```
sudo docker run -d \
--name configurator \
--restart always \
-v /~/homeassistant/.config/ \
-v /docker/configurator:/config -p 3218:3218 causticlab/hass-configurator-docker:arm
```
In /config/settings.conf (inside the container) I placed this:
```
BASEPATH: "/~/homeassistant/.config/"
ENFORCE_BASEPATH: False
```
In /usr/lib/python3.5/site-packages/hass_configurator/configurator.py I put this on lines 35 and 38:
```
BASEPATH: "/~/homeassistant/.config/"
ENFORCE_BASEPATH: False
```
In a terminal window ls -a confirms the path to my yaml files for HA is good. but when I restart configurator, it creates ~/homeassistant/.config/ inside the docker container instead of using the HA folder. I cannot find anything I've done wrong.

**Comment by danielperna84** [comment]
Don't use `~`. Provide the complete path. See if that helps.

**Comment by timothybuchanan** [comment]
Thank you for the prompt reply. The tilde is not used here as a shortcut to my home directory. The full path is /~/homeassistant/.config and that is what shows in the Bash command line. It is not ~/ but /~/. I don’t think I can expand it.

**Comment by timothybuchanan** [comment]
I used portainer to remove configurator container and image then prune –a command. I then removed the HA container and built new pointing to /home/voice/homeassistant/.config for my yaml and other config files. Testing showed that HA is working properly and using that folder for my files.

 

I then pulled and built configurator using this in terminal:

 

sudo docker run -d \

--name configurator \

--restart always \

-v /home/voice/homeassistant/.config/ \

-v /docker/configurator:/config -p 3218:3218 causticlab/hass-configurator-docker:arm

 

As you see, I used the same path as I used in building HA: /home/voice/homeassistant/.config/. I also changed configurator.py BASEPATH to point to that folder, and I inserted a file settings.conf in the /Config folder which also points to that folder. I restarted both HA and configurator several times.

 

None of that worked. Configurator still points to its root folder. It did build home/voice/homeassistant/.config in its root folder, but that directory is empty. I can create a file there, but cannot get to my yaml files for HA.

 

Is there anything else I can try, or should I conclude this just won’t work for me?

**Comment by danielperna84** [comment]
Do __NOT__ modify the `configurator.py` file. The sole purpose of the separate config file is that it is not necessary to modify any code files. ☝

That being said, I don't know what the problem is, as I don't use Docker myself. I'm assuming you're passing incorrect paths when starting the container. I don't know however what the correct values would be. If you haven't figured it out yet, please ask in [this](https://github.com/CausticLab/hass-configurator-docker) repository, as it's the one that's actually handling the Docker stuff.
