### ISSUE TITLE
Configurator Error 403 drive.google.com

### ISSUE THREAD

**Issue by Delta1977** [danielperna84/hass-configurator#221]
as i see in Chrome Dev-Console t Configurator-Addon wants access 3 URL'S from Google for Cardimages but denied with 403:
GET https://drive.google.com/uc?export=view&id=0B6wTGzSOtvNBeld4U09LQkV0c2M 403
GET https://drive.google.com/uc?export=view&id=0B6wTGzSOtvNBdFI0ZXRGb01xNzQ 403
GET https://drive.google.com/uc?export=view&id=0B6wTGzSOtvNBakk4ek1uRGxqYVE 403

source is
https://github.com/danielperna84/hass-configurator/blob/cedc9506669f85a11b419f8970ec396bd4b56b3c/hass_configurator/dev.html#L1045
https://github.com/danielperna84/hass-configurator/blob/cedc9506669f85a11b419f8970ec396bd4b56b3c/hass_configurator/dev.html#L1069
https://github.com/danielperna84/hass-configurator/blob/cedc9506669f85a11b419f8970ec396bd4b56b3c/hass_configurator/dev.html#L1081

**Comment by Taomyn** [comment]
I'm seeing the exact same thing but only if I use Brave browser which is my default. If I try the same using Edge it doesn't happen.

For me this is happening in three places: File Editor, Terminal and Log Viewer.
