### ISSUE TITLE
File editor web error

### ISSUE THREAD

**Issue by fabriziolanni** [danielperna84/hass-configurator#230]
I have this issue when open web Page
WARNING:2022-09-28 14:16:05,361:hass_configurator.configurator:Client IP banned.
INFO:2022-09-28 14:16:05,363:hass_configurator.configurator:172.30.32.1 - "GET / HTTP/1.1" 420 -

**Comment by danielperna84** [comment]
Looking at the IP address I assume this a HassOS installation. For this please ask for support in the Home Assistant community.

In any case, the error states that the IP is banned. Probably due to too many failed authentication attempts. So try restarting the add-on.
