### ISSUE TITLE
https://github.com/danielperna84/custom_homematic is not a valid add-on repository

### ISSUE THREAD

**Issue by Jensilein** [danielperna84/hass-configurator#239]
Hallo, wenn ich versuche, das repository hinzuzufügen, kommt die Fehlermeldung

`https://github.com/danielperna84/custom_homematic is not a valid add-on repository
`

Was kann ich da tun?

**Comment by danielperna84** [comment]
1. Falsches Repository. Das hier ist vom File Editor.
2. Integrationen / custom components sind keine Add-Ons.
3. Bitte dieser Anleitung folgen: https://github.com/danielperna84/custom_homematic/wiki/Installation
