### ISSUE TITLE
Add option to show folders above files in file view

### ISSUE THREAD

**Issue by markwmuller** [danielperna84/hass-configurator#241]
The file editor, when opening a file, shows all files/folders in the current directory simply alphabetically sorted. This always confuses me, and makes it hard for me to find what I'm looking for. It would be nice to have a setting that can force it to sort folders first, or sort everything equally. 

For example, Ubuntu's Nautilus has the option "Sort Folders Before Files".

**Comment by danielperna84** [comment]
That's already possible. The option for the standalone version is documented here: https://github.com/danielperna84/hass-configurator/wiki/Configuration#dirsfirst-bool

When using the Add-on, it's a single click:
<img width="786" alt="dirsfirst" src="https://github.com/danielperna84/hass-configurator/assets/7396998/769518f2-20a5-410b-8770-ac3439b68148">

**Comment by markwmuller** [comment]
Perfect, thanks for helping me find it! Is there a reason the setting is not with others (such as the keyboard VIM mode)? 

Could there be a little hint that there are more settings elsewhere? In case I'm not the only person who didn't think of the add-on configuration settings. 

Anyway, thanks for explaining!

**Comment by danielperna84** [comment]
> Is there a reason the setting is not with others (such as the keyboard VIM mode)?

Because it's a _Server_ setting. It's the backend that controls how it's returning the list of elements. The settings you are talking about are mostly specific the editor itself.

> Could there be a little hint that there are more settings elsewhere? In case I'm not the only person who didn't think of the add-on configuration settings.

As you are the first one asking the question I think that's not necessary.
