### ISSUE TITLE
congiuratore hass non apre la pagine web

### ISSUE THREAD

**Issue by dibummer** [danielperna84/hass-configurator#244]
Hi, I'm trying to configure the
hass configurator, in my home assistant core installed with docker compose on a debian basis; I have the problem that the configurator doesn't open and I can't get it to work. I attach two screenshots of the errors and my docker-
<img width="1596" alt="Screenshot 2024-03-10 alle 09 15 40" src="https://github.com/danielperna84/hass-configurator/assets/98668218/c9d402c6-15e3-4c93-abec-3f11dc65db70">

version: '3.9'
services:
  home-assistant:
    container_name: home-assistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
    - /home/deb/homeassistant:/config
    - /run/dbus:/run/dbus:ro
    environment:
    - TZ=Europe/Rome
    network_mode: host
    restart: always

  hass-configurator:
    container_name: hassconf
    image: causticlab/hass-configurator-docker
    restart: unless-stopped
    ports:
      - "3218:3218/tcp"
    volumes:
      - /home/deb/hassconf/config:/config
      - /home/deb/homeassistant/config:/hass-config

    # environment:
    #  HC_BASE_PATH: "/hass-config/"
    #  HC_ALLOWED_NETWORKS: "192.168.XX.0/24:192.168.XX.XX"
    #  HC_GIT: "True"

**Comment by danielperna84** [comment]
The syntax should be `HC_ALLOWED_NETWORKS: "127.0.0.1,192.168.0.0/16"` I believe. If that doesn't work, please open a thread in the community. I have no experience with running the Docker image.
