### ISSUE TITLE
Add tabs for editing multiple files

### ISSUE THREAD

**Issue by danielperna84** [danielperna84/hass-configurator#26]
Would be nice to be able to edit multiple files. [Tabs](http://materializecss.com/tabs.html) could be used for that.

**Comment by jmart518** [comment]
This will be awesome, implementing the tabs themselves will be a breeze.  Having multiple instances of ace editor in each tab may be tricky.

**Comment by jmart518** [comment]
Testing with static info:

<img width="1440" alt="screen shot 2017-02-26 at 2 46 57 pm" src="https://cloud.githubusercontent.com/assets/1509640/23344046/af2675fc-fc32-11e6-9017-373656c7cdc6.png">

**Comment by danielperna84** [comment]
Since [0.2.6](https://github.com/danielperna84/hass-configurator/releases/tag/0.2.6) we're displaying the name of the currently opened file in the title of the browser tab. This essentially makes using the browser-tabs very useful. It is some kind of workaround, but actually works pretty well. So I'm not sure if native tab-support within a single browser-tab provides any real benefit. Also being able to close a tab with CTRL+w works this way, whereas this would close the whole editor if the tabs where implemented within the editor. So for me this actually has been solved. I'll leave it open though in case someone want's to point out some useful benefits I don't have on my horizon yet.

**Comment by danielperna84** [comment]
Closing this now since there haven't been any comments on this. So I assume the current solution is fine for the users.
