### ISSUE TITLE
Mobile: miscellaneous problems

### ISSUE THREAD

**Issue by klarjr** [danielperna84/hass-configurator#27]
On Android 7.7.1 Nexus 6P I'm unable to highlight/select specific text to copy, cut, or paste. When attempting to select text, it shows the two pull tabs that normally allow adjusting of the selected text. This doesn't work. When trying to adjust the selection, it will either select none or everything making it impossible to copy/cut text. Paste does work.

**Comment by danielperna84** [comment]
I have tested your observation and can confirm the bug. The bug however is not caused by our implementation, but is already present in the [Ace Editor](https://ace.c9.io/) itself. There are quite a few issues regarding mobile support, as you can see here: https://github.com/ajaxorg/ace/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20mobile

So for this to be fixed, we need to wait for a new version of the editor.

**Comment by MichaelBergquistSuarez** [comment]
Couldn't there just be an option for deactivating  the Ace editor?

That would be a good thing regardless of whether the bug get fixed or not:
- Some us prefer other tools
- There will most likely be more problems in the future. A disable option would minimize the those problems.

**Comment by danielperna84** [comment]
> Couldn't there just be an option for deactivating the Ace editor?

Which purpose would the configurator serve without the ability to modify the configuration files? That's its primary job. The only option would be to __replace__ the editor with something different. But that won't happen for sure.

**Comment by MichaelBergquistSuarez** [comment]
> > Couldn't there just be an option for deactivating the Ace editor?
> 
> Which purpose would the configurator serve without the ability to modify the configuration files? That's its primary job. The only option would be to **replace** the editor with something different. But that won't happen for sure.

Hmm. I must have misunderstood the purpose of hass-configurator then.

I was thinking it's HTML, so you could edit text with a `<textarea>`? The built-in text editor in my phones browser would do just fine (and better) for me. So I thought that the Ace editor just the text editing part. But judging from your answer I guess not?

The reason for me using hass-configurator was simply to easily access the configuration files from my phone, to get things up and running and for simple experimentation quickly and easy from my bed.

I did *not* install this to get syntax highlighting etc. I simply wanted to play around with my config a bit before configuring SSH etc.

But I'm new to Home Assistant, so I said; I may have misunderstood the purpose of this add-on.

What would be your recommendation for new users that just would like to play around a bit from the phone?

**Comment by danielperna84** [comment]
@MichaelBergquistSuarez 
When I started the configurator it was just that. But users wanted syntax highlighting and yaml-linting to ensure that they don't makes errors. Back then restarting Home Assistant with a broken configuration could easily result in Home Assistant not starting at all. So it's a visual safeguard to protect users from breaking their systems.
Apart from that it makes navigating your configuration easier if you can fold code-blocks, or just simply use some of the other features the Ace Editor provides.

That being said, even though generally the configurator can be used on mobile devices, the target clients are _real_ computers. And I'm sure you can look at your configuration right now without any problems. It's small features like copy & paste that are a but problematic. In my opinion that's a minor inconvenience compared to the features capable client devices gain.

**Comment by danielperna84** [comment]
For me copy & paste seems to work on android now. Although a bit unintuitive.
