### ISSUE TITLE
Error reading configuration.yaml

### ISSUE THREAD

**Issue by Pho7ography** [danielperna84/hass-configurator#29]
hi,

when a try to open my configuration file i get this error:

'ascii' codec can't decode byte 0xc2 in position 2231: ordinal not in range(128)

thanks

**Comment by danielperna84** [comment]
You probably have non-ASCII letters in your configuration. That's probably something where you have set the friendly name of an entity. So the workaround would be to have your configuration only contain ASCII letters.
It's still a bug though, since the editor shouldn't be limited to only editing ASCII files. Thanks for reporting that.

**Comment by danielperna84** [comment]
I have tested functionality with german letters like `öäü` (which are not ASCII), and I didn't have any problems opening the file. Is there anything else special about your file? Which language / alphabet is used besides the usual abcdefg...?

**Comment by Pho7ography** [comment]
I found the error, is this line:

unit_of_measurement: '°C'

the small ° from Celsius .

**Comment by danielperna84** [comment]
Works for me. For testing I've created a new file using the configurator, copied and pasted the exact same line you've posted here, saved the file, opened it again, all without any issues.

Could it be, that before using the configurator you have edited your configuration files using SMB and some windows-editor? Maybe the editor used some other encoding, which got directly transferred to your HASS machine. The configurator should be able to read it, but it's kind of hard to debug this without the file that's causing the problems.

**Comment by Pho7ography** [comment]
strange, i have edit the file, put the ° using the configurator, save, and open again and i get the same error, i'm using  safari for that.
Remove the °, and is ok again.

**Comment by danielperna84** [comment]
I have now tested it with Safari on a german MacBook, and it work's there too. What's your system language?

**Comment by Pho7ography** [comment]
The system is in english and portuguese keyboard.

**Comment by danielperna84** [comment]
Does your keyboard layout look like this, and is the key I've marked red the one you are using to enter the ° sign?
<img width="777" alt="pkb" src="https://cloud.githubusercontent.com/assets/7396998/23766031/9a501b7c-0503-11e7-8c8b-c132b04dd80c.png">

**Comment by Pho7ography** [comment]
Yes looks like that one, but is a compact one. mac wireless keyboard.
(ª º) key near P key.

**Comment by danielperna84** [comment]
Ok. The key you are using internally isn't the correct one for degrees. The degrees-character has an ASCII value of 176. The letter you are using ([masculine ordinal indicator](https://en.wikipedia.org/wiki/Ordinal_indicator#Masculine), [encoding details](https://en.wikipedia.org/wiki/Degree_symbol#Encoding)) has 186. Just out of curiosity, please copy and paste this degree-character into the configurator and tell me if it works: `°`.

**Comment by Pho7ography** [comment]
The same error
when i try to edit directly the file using nano in rpi the cursor stop in the character (º) two times, is like that is not one char, but two char in the same place.

**Comment by danielperna84** [comment]
Since you're using mac: please open the terminal and enter the command `locale`. What's the output you get?

**Comment by Pho7ography** [comment]
Mac:
LANG=
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
RPI:
LANG=en_US
LANGUAGE=
LC_CTYPE="en_US"
LC_NUMERIC="en_US"
LC_TIME="en_US"
LC_COLLATE="en_US"
LC_MONETARY="en_US"
LC_MESSAGES="en_US"
LC_PAPER="en_US"
LC_NAME="en_US"
LC_ADDRESS="en_US"
LC_TELEPHONE="en_US"
LC_MEASUREMENT="en_US"
LC_IDENTIFICATION="en_US"
LC_ALL=

**Comment by danielperna84** [comment]
For comparison here's my output:
Mac:
```
LANG="de_DE.UTF-8"
LC_COLLATE="de_DE.UTF-8"
LC_CTYPE="de_DE.UTF-8"
LC_MESSAGES="de_DE.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_ALL=
```

RPI:
```
LANG=de_DE.UTF-8
LANGUAGE=
LC_CTYPE="de_DE.UTF-8"
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_COLLATE="de_DE.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_MESSAGES="de_DE.UTF-8"
LC_PAPER="de_DE.UTF-8"
LC_NAME="de_DE.UTF-8"
LC_ADDRESS="de_DE.UTF-8"
LC_TELEPHONE="de_DE.UTF-8"
LC_MEASUREMENT="de_DE.UTF-8"
LC_IDENTIFICATION="de_DE.UTF-8"
LC_ALL=
```

I'm no expert on that topic, so I don't really know what to do about that. But when comparing my output to yours, your Mac and your RPI aren't in sync regarding the system-encoding. So I come to believe it's actually a local issue with your machine.
Do you have access to other machines? Maybe Windows for comparison, and from a mobile device too if possible. With those you could check if the problem persists. If so, then it would be your Mac that is causing the problem.

**Comment by Pho7ography** [comment]
ok, i gone try using other machines.
thanks

**Comment by danielperna84** [comment]
Did you make any progress with your issue or does it still persist?
