### ISSUE TITLE
carbonads referenced

### ISSUE THREAD

**Issue by danielperna84** [danielperna84/hass-configurator#34]
I have noticed, that either materialize or the material design icons contact some ad-related stuff in the background, which doesn't work when a JavaScript blocker and / or Ghostery is active.

**Comment by jmart518** [comment]
Wow hmm, I just took a peek at `https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/css/materialize.min.css` `https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/js/materialize.min.js` and wasn't able to find reference to carbonads

**Comment by danielperna84** [comment]
Yeah, might be the new material icons we switched to instead. Not sure about this. This doesn't have a high priority as well. Just wanted to have this noted somewhere.
