### ISSUE TITLE
probably a user error Imports not found

### ISSUE THREAD

**Issue by zdavis28** [danielperna84/hass-configurator#41]
getting this when running configurator. Any idea?

pi@raspberrypi:/home/homeassistant/.homeassistant $ sudo ./configurator.py
./configurator.py: 1: ./configurator.py: import: not found
./configurator.py: 2: ./configurator.py: import: not found
./configurator.py: 3: ./configurator.py: import: not found
./configurator.py: 4: ./configurator.py: import: not found
./configurator.py: 5: ./configurator.py: import: not found
./configurator.py: 6: ./configurator.py: import: not found
./configurator.py: 7: ./configurator.py: import: not found
./configurator.py: 8: ./configurator.py: import: not found
./configurator.py: 9: ./configurator.py: import: not found
./configurator.py: 10: ./configurator.py: import: not found
./configurator.py: 11: ./configurator.py: import: not found
./configurator.py: 12: ./configurator.py: import: not found
from: can't read /var/mail/string
from: can't read /var/mail/http.server
./configurator.py: 15: ./configurator.py: import: not found
from: can't read /var/mail/urllib.parse
./configurator.py: 19: ./configurator.py: LISTENIP: not found
./configurator.py: 20: ./configurator.py: LISTENPORT: not found
./configurator.py: 22: ./configurator.py: BASEPATH: not found
./configurator.py: 24: ./configurator.py: SSL_CERTIFICATE: not found
./configurator.py: 25: ./configurator.py: SSL_KEY: not found
./configurator.py: 27: ./configurator.py: HASS_API: not found
./configurator.py: 29: ./configurator.py: HASS_API_PASSWORD: not found
./configurator.py: 31: ./configurator.py: CREDENTIALS: not found
./configurator.py: 34: ./configurator.py: ALLOWED_NETWORKS: not found
./configurator.py: 36: ./configurator.py: BANNED_IPS: not found
./configurator.py: 38: ./configurator.py: BANLIMIT: not found
./configurator.py: 40: ./configurator.py: GIT: not found
./configurator.py: 43: ./configurator.py: LOGLEVEL: not found
./configurator.py: 44: ./configurator.py: Syntax error: "(" unexpected

**Comment by danielperna84** [comment]
Does the first line of your configurator.py contain `#!/usr/bin/python3`? The output is looking like your system doesn't know that's a Python script. And that's exactly what the `#!/usr/bin/python3` is there for.

**Comment by danielperna84** [comment]
Did you get the problem fixed?

**Comment by danielperna84** [comment]
I assume the problem has been solved. Closing the issue.
