### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by FireWAV3** [danielperna84/hass-configurator#43]
hello I have this issue on Hass.io:
starting version 3.2.2
INFO:2017-07-29 16:13:06,003:__main__:Starting server
Traceback (most recent call last):
  File "/configurator.py", line 3494, in <module>
    main(sys.argv[1:])
  File "/configurator.py", line 3484, in main
    server_side=True)
  File "/usr/lib/python3.6/ssl.py", line 1142, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python3.6/ssl.py", line 741, in __init__
    self._context.load_cert_chain(certfile, keyfile)
FileNotFoundError: [Errno 2] No such file or directory
pls help 
[I found no other way to conntact you]

**Comment by danielperna84** [comment]
I am not a active Hass.io user, so I am not sure how to solve the problem. The error itself is telling you, that it is trying to load a SSL certificate / key, but is unable to find it at the sepcified path. I don't have a testing-machine at hand to have a look at it. But if I remember correctly, you're given the options to specify both paths for the certificate and the key. So you could either leave both empty and use it without encryption, or you figure out what the correct values for those two options would be.

Hope this helps.

**Comment by FireWAV3** [comment]
Ok will try it thanks for your hepl

**Comment by Robert-Arciszewski** [comment]
Key.pem, Cert.pem should be in start catalogue. Then it works.

**Comment by Zzebb** [comment]
> 

What do you mean by 'Start catalogue'. Sorry i am a junior dev :)
