### ISSUE TITLE
Update jQuery and Ace Editor

### ISSUE THREAD

**Issue by danielperna84** [danielperna84/hass-configurator#46]
The latest CDN version of jQuery version 2 is 2.2.4, while we are on 2.1.1. Do we want to switch to jQuery 3? Compatibility with materialize and the Ace Editor would need to be tested though.
The safe route would be to just update jQuery with:
```<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>```

Regarding the Ace Editor we are on version 1.2.6, the latest CDN version is [1.2.8](https://cdnjs.com/libraries/ace/). This should be updated.

@jmart518 do you want to take care of this while you're at it? :)

**Comment by jmart518** [comment]
I recently migrated to HASS.io, is there a way to test with the dev.html on this setup?

Can you please double check that everything is working for you with materializecss 100.1?  I just realized that any changes I make to the configurator.py get reverted after a home assistant restart as well as a reboot.

**Comment by danielperna84** [comment]
I'm not sure if it's easy to test wth hassio. My guess would be, that modifying he files could lead to issues with persistence, just like you experience them.

My suggestion would be, to just test the configurator on a different machine. I have it running on Windows while developing, and it should also work on Macs without any issue. It's designed to be cross-platform. Or at least should be.

The new materialize is working for me. Before merging I've pulled the changes to my pi. Looking at the filebrowser and clicking around a bit all worked like it should.

**Comment by danielperna84** [comment]
Update: Materialize + jQuery 3 shouldn't be an issue, since the getting started guide references 3 itself: http://materializecss.com/getting-started.html

**Comment by jmart518** [comment]
Good deal, I'll do some testing later today and get back to you

**Comment by jmart518** [comment]
Looks like version 0.100.1 broke modals, can you verify your end?

**Comment by danielperna84** [comment]
You are right. Had the dev-flag still on and was looking at the old version. With the new materialize the modals are broken.
