### ISSUE TITLE
YAML Lint

### ISSUE THREAD

**Issue by AtoxIO** [danielperna84/hass-configurator#62]
Too often a small typo can cause a whole lot of grief, wouldn't a built-in YAML linter be a great addition to help especially newbies but also veterans with clumsy fingers?

**Comment by danielperna84** [comment]
It for sure would be. But that would require an additional dependency on the server-side and make things much more complicated. Especially since it wouldn't be live checking. You'd have to save and let the backend check if everything is ok. And for that you could actually just have Home Assistant open in another tab and use the config validation from there. That's far more efficient since it knows more about the internals.
There once was a button to trigger a config check from the configurator, but then the API changed and it didn't work anymore. If we could figure out what HASS is doing and if we can replicate and call that from the configurator, that would be the implementation that makes the most sense to me.

**Comment by AtoxIO** [comment]
I was thinking a client-side yaml linter, and a simple checkmark/warning if the YAML was invalid. I can look into it if you want.

**Comment by danielperna84** [comment]
I did a quick search for YAML linters in JS, and at least the most prominent ones where Node.js things. Since I've never worked with that I don't know if that can be used without the proper backend. If so, then that indeed would be an alternative.

**Comment by AtoxIO** [comment]
Okay, I found a relatively simple solution.

Just add https://cdnjs.cloudflare.com/ajax/libs/js-yaml/3.10.0/js-yaml.js to the list of scripts and then the following code does the trick:

    editor.getSession().on('change', function(e) {
        try {
            var doc = jsyaml.safeLoad(editor.getValue(), 'utf8');
            console.log("Correct YAML");
        } catch (err) {
            console.log("Incorrect YAML");
            console.log(err);
        }
    });

Now I need
1. to detect if we are currently editing YAML
2. a good place in the GUI to put the checkmark/error box with info
3. to probably add a timer to prevent rapid checking, instead waiting a few seconds after the last input to verify the YAML.

**Comment by danielperna84** [comment]
Sounds great! :)

2. `$('#currentfile').val().match(".yaml$")` would be an easy option.
3. I'd either use [toasts](http://materializecss.com/dialogs.html) or [modals](http://materializecss.com/modals.html). I haven't seen the error output of js-yaml, but I assume it could become rather big. So a modal would make more sense.
4. Either that, or maybe only lint when saving the file. The notifications of incorrect yaml whenever they stop typing could be distracting when it's just something like includes, or at least bugging when thinking about figuring out what to do. So I would favor just checking when saving. When an error is detected, display it in a warning-modal and ask the user if he want's to proceed saving or rather fix the error.

**Comment by AtoxIO** [comment]
What about this, an icon after the filename, aligned to the right. When it's an error you can click it to get a modal with the detailed error.

![Example](https://i.imgur.com/TI9HTvj.png)

**Comment by danielperna84** [comment]
Looking nice. But then there should also be an icon indicating that the state is uncertain. Like on every keyup event it turns to a questionmark or something like that, and when the check is finished it becomes the cehckmark or some failed-icon. That way the user has a visual hint about what is currently going on.

**Comment by danielperna84** [comment]
No, include and secret are the only ones that I can think of. How about templates? Do they work out of the box?

**Comment by AtoxIO** [comment]
Yes templates work perfectly, I submitted a pull request with the finished product.

**Comment by danielperna84** [comment]
Thanks a lot. Works like a charm. Already released the new version which includes your work. :)
