### ISSUE TITLE
default directory is /

### ISSUE THREAD

**Issue by foxsam21** [danielperna84/hass-configurator#63]
I ran configurator manually and it had .homeassistant/ as the root dir. but when I added the systemd script and started it the root dir is / . How can I get the default root back to .homeassistant?

**Comment by danielperna84** [comment]
Have a look at the [BASEPATH](https://github.com/danielperna84/hass-configurator#basepath-string) option. That should do what you want.

**Comment by foxsam21** [comment]
:( you're right. I did set basepath like I was supposedd to and thats why I got confused. After your post I double checked and basepath was still set. When I checked the systemd service file I forgot to pass on the configuration file that set the basepath so of course it did not work! sometime you just have to start from scratch.
thanks.
