### ISSUE TITLE
Hiding the filebrowser requires click in specific area

### ISSUE THREAD

**Issue by danielperna84** [danielperna84/hass-configurator#79]
As reported [here](https://community.home-assistant.io/t/hass-io-configurator-screen-is-dimmmed-greyed-out/41804) and also already noticed by myself and others, closing the filebrowser requires some clicking around until it finally reveals the editor. This is caused by the swiping function that's very useful for mobile devices. On desktops though this results in a huge area where clicking has no effect.

To visualize this you can open the JavaScript console and execute the command:
```javascript
$('.drag-target').css("border-left", "1px solid #f00")
```

Only clicks to the left of that line hide the filebrowser because that swiping-div blocks the clicks.

I don't know how that should be fixed. If anybody knows what to do a PR to fix this issue would be very appreciated.

@jmart518 since you're our UI guy, could you have a look at it?

**Comment by jmart518** [comment]
You bet, I've been meaning to take a look at that for a while now.  It can be quite annoying
