### ISSUE TITLE
ASCII Decode

### ISSUE THREAD

**Issue by manuel-jrs** [danielperna84/hass-configurator#80]
I added "ñ" character in a group name, then I save the changes. The "ñ" looks fine in HASS but when I re-opened the file it shows this message:

``'ascii' codec can't decode byte 0xc3 in position 282: ordinal not in range(128)``

**Comment by danielperna84** [comment]
Could you provide detailed steps how to reproduce this?
What I have tried:
- Add an empty file
- Insert usual test
- Save
- Open again
- Copy the character from here and paste it into the file
- Save
- Open again

I had no trouble in doing all this. Did you enter that character from the automation editor oder customization that is integrated into Home Assistant?

**Comment by manuel-jrs** [comment]
1. I opened "groups.yaml", in the group name, I set "Baño #1", then I saved it.
![screenshot_1](https://user-images.githubusercontent.com/656076/36048842-316965da-0da6-11e8-93d7-cbe1ffe6d8e4.png)
2. I re-opened the file "groups.yaml" and it shows that error:
![screenshot_3](https://user-images.githubusercontent.com/656076/36048895-5f462b46-0da6-11e8-93f8-78f9eba5b89c.png)
![screenshot_4](https://user-images.githubusercontent.com/656076/36048948-9c88e3fe-0da6-11e8-9aa1-3174b5dc2353.png)

**Comment by danielperna84** [comment]
I think this might be the same problem that has been reported previously, but didn't make any progress: https://github.com/danielperna84/hass-configurator/issues/29
