### ISSUE TITLE
SSL for configurator

### ISSUE THREAD

**Issue by TheZoker** [danielperna84/hass-configurator#81]
I'm using my HA via custom domain https://ha.domain.com with the LetsEncrypt addon installed.

Now I tried to include the configurator within my HA dashboard, I used the panel_iframe.
The issue now is, that because I connect via SSL and the configurator is loaded http, I get an error.

To fix this, I also created a port forwarding with 3218 to the configurator. But everytime I try to access the configurator via https://ha.domain.com:3218 I get an empty response.

1. How can I add my domain to the whitelist, since it's not a IP, but a domain?
2. How can I enable the ssl with [LetsEncrypt addon](https://home-assistant.io/addons/lets_encrypt/)? 
Like this?
```
  "certfile": "/ssl/fullchain.pem",
  "keyfile": "/ssl/privkey.pem",
  "ssl": true,
```

Thank you!

**Comment by danielperna84** [comment]
1. You can't add domains to the whitelist. That's a technical property of how TCP/IP works. So you have no other choice but allowing access from everywhere.
2. I don't use hass.io. It could be like that. If these are the paths you set for Home Assistant, then they should work for the configurator as well.

**Comment by TheZoker** [comment]
Ah alright. 

But when I set it the same as my HA config, I get this error:
![screenshot_2018 02 28_00h22m19s_001_](https://user-images.githubusercontent.com/1368405/36761034-89ab1a4c-1c1d-11e8-9c2f-1d832cabbdeb.png)

**Comment by danielperna84** [comment]
Please have a look at the forum. Somebody else had a similar issue. If someone is able to help, then that's the place to go.

**Comment by TheZoker** [comment]
If anyone else has this issue:
https://community.home-assistant.io/t/repository-hass-configurator/17838/74
