### ISSUE TITLE
Help with network security setup?

### ISSUE THREAD

**Issue by poldim** [danielperna84/hass-configurator#82]
I've setup the [HASS Configurator](https://github.com/danielperna84/hass-configurator) and have it working on my LAN with it's IP.  But I add the panel_iframe for it using the LAN IP, I can't access it if I'm accessing HA via the WAN domain.

I was trying to think through the security settings and how it needs to be set up to be safe.  Currently, I have a domain and run letsencrypt reverse proxy to provide SSL certs at home.domain.com.  This means I don't have HA config setup with SSL certs as letsencrypt handles them.  

Do I need to create another subdomain and target in letsencrypt pointing to the configurator port?

**Comment by poldim** [comment]
I noticed that is how HA behaves in my setup.  For example, I have two iframes: ide + configurator.  The URL for these are subdirectories off of my main HA base URL based on the [panel name](https://home-assistant.io/components/panel_iframe/#panel_name).  It'd be nice if in this configuration HA could pass it's authorized credentials to Configurator.

IE:

> base url: https://home.domain.com
> ide url: https://home.domain.com/ide
> configurator url: https://home.domain.com/configurator


    panel_iframe:
      ide:
        title: AIRBNB
        icon: mdi:home-heart
        url: !secret airbnb_url
      configurator:
        title: Editor
        icon: mdi:wrench
        url: !secret configurator_url

**Comment by danielperna84** [comment]
You can include credentials directly in the URL like this: `https://username:password@home.domain.com/configurator`
