### ISSUE TITLE
Configurator loads external iframes on page load (with ads and analytics)

### ISSUE THREAD

**Issue by markus-k** [danielperna84/hass-configurator#85]
I was just wondering why my uBlock Origin is blocking hundrets of requests on my local HASS instance, some of those requests targeting google analytics and carbonads. 

Turns out the HASS configurator loads a bunch of iframes with content from the hass website and others, which are creating those requests when the configurator is loaded.

Those iframes should only be loaded when they are actually used, not unconditionally on page load.

**Comment by danielperna84** [comment]
This is related to https://github.com/danielperna84/hass-configurator/issues/34

Is there a way to load iframes on demand? I haven't checked, and so far I was under the impression that's not possible without dynamically creating the iframe element.

**Comment by jb137** [comment]
Would it be possible to skip using externals source all together and include everything in the component? This way I can use the plug-in without a live internet connection as well.

**Comment by danielperna84** [comment]
No, that wouldn't make sense. I would have to include two whole websites which update rather frequently. For one this would require continuous updates to the configurator just for the website updates (which aren't core functionality). Additionally the configurator itself is designed to be easily deployed in it's standalone version, which is just a single file.
The only option I see would be to remove this. But as it happens people actually gave positive feedback on having the documentation and the icons just one click away.

**Comment by mik-at** [comment]
Can we have options to enable/disable those two websites in the settings?

**Comment by jb137** [comment]
Nice solution. Thank you.
