### ISSUE TITLE
Delay Action input error

### ISSUE THREAD

**Issue by Gluwc** [danielperna84/hass-configurator#91]
When typing something into the Delay value box when trying to create an automation and removing everything from the value box the whole action turns into this error: 

**_Unsupported action:
{}_**

After this I'm forced to remove the Action and recreate a new one.

**Comment by danielperna84** [comment]
I think you may be confusing the HASS Configurator with the integrated configuration UI of Home Assistant. This is a standalone application for editing text-files. There is no action editor in this configurator. So I think your issue actually belongs here: https://github.com/home-assistant/home-assistant-polymer
