### ISSUE TITLE
Setup GIT Public Key help wanted

### ISSUE THREAD

**Issue by smccloud** [danielperna84/hass-configurator#92]
I would like to use the Configurator to push changes to my GitHub repo.  However, I am not sure how to set the public key in it.  Are there directions on how to set this up somewhere.

**Comment by danielperna84** [comment]
This is not directly related to the configurator. Googeling returned a few promising results. This for example: https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/

**Comment by smccloud** [comment]
Sorry, I wrote it wrong.  I mean configuring the configurator to use a public key already setup in GitHub.  SO adding the private key to it.

**Comment by danielperna84** [comment]
In that case I assume all that it takes is placing the private key in `~/.ssh/id_rsa` with the correct permissions (600 I think). The homedir depends on which user is used to run the configurator. I have it set up like this and push to a local SSH repository. If GitHub has no other requirements, then this should be all it takes.

**Comment by smccloud** [comment]
So it isn't working, but I could very well be doing something wrong.

**Comment by danielperna84** [comment]
Does a manual `git push` in the terminal work? As long as it doesn't work manually, the configurator won't be able to push as well.

**Comment by smccloud** [comment]
Manual push in the terminal works fine.

I get the following error.
`Cmd('git') failed due to: exit code(128)
  cmdline: git push --porcelain origin
  stderr: 'faltal: cannot run ssh: No such file or directory
fatal: unable to fork'
/config`

**Comment by smccloud** [comment]
Yes, I am running hassio.  Its not a huge deal, just be nice to be able to do it.  In any event, it will at least show me that I have changes to commit.

**Comment by darkkatarsis** [comment]
This same problem. Im using hassio and git push working fine from terminal. Is there a chance for push to work directly by addon?

**Comment by danielperna84** [comment]
Please use the forum for such questions. I don't use hassio, so I can't answer the question. And nobody else will ever look into this issue.
