### ISSUE TITLE
"Permission denied" on ".git/COMMIT_EDITMSG" when using "git commit/add" menu item

### ISSUE THREAD

**Issue by ayavilevich** [danielperna84/hass-configurator#94]
Using latest hassbian with configurator. Liking it.
Configurator loads automatically with systemd.

I defined the hass configuration folder in git manually. Using sudo git commands (as pi user has no write access there). All works if I add/commit/push from the command line. I do need to specify password for repository if I am pushing.
Now if I issue a "git commit" from the configurator interface then I get a permission error on COMMIT_EDITMSG.

```
[Errno 13] Permission denied: '/home/homeassistant/.homeassistant/.git/COMMIT_EDITMSG'
/home/homeassistant/.homeassistant
```

If I issue a "git add" on some file I will get a permission error on some other file.

Am I doing anything wrong? Is there a bug or a way to fix this?

**Comment by danielperna84** [comment]
Well, which user is running the configurator? You have created the repository as root, so the configurator needs to run as root as well if you want it to have permission to work with the repository. Which wouldn't be the best idea. I'd rather add the user that's running the configurator to a group that has write-permissions on your repository.

**Comment by ayavilevich** [comment]
Ok, that was a good pointer. I used the template and it specifies ``User=homeassistant`` for the service. I am not familiar with unix/linux type permission that much. Can you advise what commands to use to change ``.git`` folder so the homeassistant user can write to it?

**Comment by danielperna84** [comment]
It would have been the easiest if you hadn't initially created the repository manually. The configurator has a button for creating the repository, and in that case all the permissions will be fine.
To fix this manually though this command should work:
`chown -R homeassistant:homeassistant /path/to/your/repository`

**Comment by ayavilevich** [comment]
Excellent! Works now.
Created the repository before configuring the configurator, so had to fix it up now.
Just learned that I can ``sudo su -s /bin/bash homeassistant``, it would have made it all easier if I knew to do that before. Thanks.
