### ISSUE TITLE
Feature Request: Open file by URL

### ISSUE THREAD

**Issue by OttoWinter** [danielperna84/hass-configurator#95]
Hi, first of all thanks for this absolutely awesome add-on!

I myself am developing another add-on for HassIO (an [esphomeyaml](https://esphomelib.com/esphomeyaml/index.html) HassIO add-on). The add-on will require users to edit YAML configuration files too, like with Home Assistant. These YAML configuration files (stored under `/config/esphomeyaml/...` and therefore already accessible by Hass Configurator) are compiled into binaries and uploaded to a device and it's all controlled from a simple web interface. 

Because navigating to this path (for example `/config/esphomeyaml/livingroom.yaml`) is not a perfect UX, ideally I think it would be great if I could create a cross-link to Hass Configurator like `http://hassio.local:3218/config/esphomeyaml/livingroom.yaml` :)

Please excuse me if this already possible, I wasn't able to find such a feature using the limited search I just did of this repo.

**Comment by danielperna84** [comment]
I have added this functionality in the new version.
The way this is used is by appending `/?loadfile=/path/to/file` to the base URL of the configurator. So for example `https://192.168.1.123:3218/?loadfile=/home/homeassistant/.homeassistant/configuration.yaml`.
The hass.io addon is not yet updated though. So keep an eye on that.
