### ISSUE TITLE
Any advice on what else I need to add to my nginx config to get it to work?

### ISSUE THREAD

**Issue by poldim** [danielperna84/hass-configurator#96]
I've tried all sorts of this to get this to work behind nginx.  Any hints at the correct proxy config?  The UI comes up but there is not content on the WAN connection, however, accessing through the LAN IP presents a fully working configurator.

```
location / {
proxy_pass http://192.168.1.100:3218/;
proxy_set_header Host $host;

proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
}
```

**Comment by danielperna84** [comment]
> but there is not content on the WAN connection

So just a blank page? I don't nginx myself, so I'm not sure what the issue could be. First thing I would do is take a look at the error log of nginx. And also at the log of the configurator when you try to access it. If the log of the configurator doesn't show anything, then it already fails at nginx. If it does show something, then maybe the security-options of the configurator have to be adjusted.
It might also be a good idea to post this question in the thread in the HASS forum. There may be others there that could help better with this than I can do.

**Comment by poldim** [comment]
Yes, it's definitely not a problem with the configurator.  Does the configurator use websockets or an API at a specific sub URL?  I know my UniFi controller [requires passing a /wss directory](https://community.ubnt.com/t5/UniFi-Wireless/Unifi-Controller-behind-nginx-proxy-Server-log-LocalHost/td-p/2020122) to facilitate websockets.  Is there anything like that requires back and forth comms?

**Here are the example of what I mean:**

<img width="788" alt="screen shot 2018-05-27 at 3 52 56 pm" src="https://user-images.githubusercontent.com/16869713/40591466-c63ed400-61c6-11e8-8ca5-0f756cd9f73f.png">


<img width="788" alt="screen shot 2018-05-27 at 3 53 10 pm" src="https://user-images.githubusercontent.com/16869713/40591467-ca853ff4-61c6-11e8-953d-91459a706b73.png">

**Comment by danielperna84** [comment]
To me that looks perfectly fine. It even loads you entities. I suspect there's just a little confusion: the configurator loads the last opened file using local storage. That storage is bound to the domain it is accessed from. So it will always load something different depending on how you access it. Try opening a file manually when using you wan ip.

**Comment by danielperna84** [comment]
Any news on this?

**Comment by poldim** [comment]
I had to take the server down to do some hardware upgrades, to my surprise,
when I just brought it back up, it's working without any additional config!
